/* tslint:disable */
/* eslint-disable */
/**
 * Splashify Pro API
 * REST endpoints for three product surfaces: 1. **Public API** under /public/_* — WhatsApp messaging, contacts, conversations, transactional email, Meta Conversions API. Authenticate with sk_live_… keys. 2. **Partner Email API** under /partner/email/_* — AWS-SES-shaped resold email platform: identities, configuration sets, templates, suppression, send, send-template, send-bulk, send-raw, quotas, stats, reputation, events. Authenticate with pk_live_… keys. 3. **App API** under /app/_* — the same surface the customer dashboard and the CLI/OpenClaw integrations use, authenticated with either an app session or an oc_live_… access token (`splashify auth login` / Settings → Developer → Access Tokens). Coverage here is partial — only endpoints touched by integrator reports are annotated so far, not the full surface. SDKs for Node.js, Python, and PHP are auto-generated from this spec.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@splashifypro.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
} from '../models/index';

export interface AppActivityLogsGetRequest {
    action?: string;
    entityType?: string;
    entityId?: string;
    actorId?: string;
    limit?: number;
    cursor?: string;
}

/**
 * ActivityApi - interface
 * 
 * @export
 * @interface ActivityApiInterface
 */
export interface ActivityApiInterface {
    /**
     * Creates request options for appActivityLogsGet without sending the request
     * @param {string} [action] Filter by action
     * @param {string} [entityType] Filter by entity type
     * @param {string} [entityId] Filter by entity id
     * @param {string} [actorId] Filter by actor id
     * @param {number} [limit] Page size, default 50, max 200
     * @param {string} [cursor] Opaque cursor from a previous response\&#39;s next_cursor
     * @throws {RequiredError}
     * @memberof ActivityApiInterface
     */
    appActivityLogsGetRequestOpts(requestParameters: AppActivityLogsGetRequest): Promise<runtime.RequestOpts>;

    /**
     * Paginated audit trail of account activity. total is a real row count; page with cursor/next_cursor, not offset.
     * @summary List activity logs
     * @param {string} [action] Filter by action
     * @param {string} [entityType] Filter by entity type
     * @param {string} [entityId] Filter by entity id
     * @param {string} [actorId] Filter by actor id
     * @param {number} [limit] Page size, default 50, max 200
     * @param {string} [cursor] Opaque cursor from a previous response\&#39;s next_cursor
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ActivityApiInterface
     */
    appActivityLogsGetRaw(requestParameters: AppActivityLogsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Paginated audit trail of account activity. total is a real row count; page with cursor/next_cursor, not offset.
     * List activity logs
     */
    appActivityLogsGet(requestParameters: AppActivityLogsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

}

/**
 * 
 */
export class ActivityApi extends runtime.BaseAPI implements ActivityApiInterface {

    /**
     * Creates request options for appActivityLogsGet without sending the request
     */
    async appActivityLogsGetRequestOpts(requestParameters: AppActivityLogsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['action'] != null) {
            queryParameters['action'] = requestParameters['action'];
        }

        if (requestParameters['entityType'] != null) {
            queryParameters['entity_type'] = requestParameters['entityType'];
        }

        if (requestParameters['entityId'] != null) {
            queryParameters['entity_id'] = requestParameters['entityId'];
        }

        if (requestParameters['actorId'] != null) {
            queryParameters['actor_id'] = requestParameters['actorId'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/app/activity-logs`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Paginated audit trail of account activity. total is a real row count; page with cursor/next_cursor, not offset.
     * List activity logs
     */
    async appActivityLogsGetRaw(requestParameters: AppActivityLogsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.appActivityLogsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Paginated audit trail of account activity. total is a real row count; page with cursor/next_cursor, not offset.
     * List activity logs
     */
    async appActivityLogsGet(requestParameters: AppActivityLogsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.appActivityLogsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
