/* tslint:disable */
/* eslint-disable */
/**
 * Splashify Pro API
 * REST endpoints for three product surfaces: 1. **Public API** under /public/_* — WhatsApp messaging, contacts, conversations, transactional email, Meta Conversions API. Authenticate with sk_live_… keys. 2. **Email API** under /partner/email/_*. Email sending for developers: identities, configuration sets, templates, suppression, send, send-template, send-bulk, send-raw, quotas, stats, reputation, events. Authenticate with pk_live_… keys. 3. **App API** under /app/_* — the same surface the customer dashboard and the CLI/OpenClaw integrations use, authenticated with either an app session or an oc_live_… access token (`splashify auth login` / Settings → Developer → Access Tokens). Coverage here is partial — only endpoints touched by integrator reports are annotated so far, not the full surface. SDKs for Node.js, Python, and PHP are auto-generated from this spec.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@splashifypro.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
} from '../models/index';

export interface PublicBroadcastsIdAutoRetargetDeleteRequest {
    id: string;
}

export interface PublicBroadcastsIdAutoRetargetGetRequest {
    id: string;
}

export interface PublicBroadcastsIdAutoRetargetPostRequest {
    id: string;
    body: object;
}

/**
 * BroadcastsApi - interface
 * 
 * @export
 * @interface BroadcastsApiInterface
 */
export interface BroadcastsApiInterface {
    /**
     * Creates request options for publicBroadcastsIdAutoRetargetDelete without sending the request
     * @param {string} id Broadcast id
     * @throws {RequiredError}
     * @memberof BroadcastsApiInterface
     */
    publicBroadcastsIdAutoRetargetDeleteRequestOpts(requestParameters: PublicBroadcastsIdAutoRetargetDeleteRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Cancel an automatic retarget
     * @param {string} id Broadcast id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BroadcastsApiInterface
     */
    publicBroadcastsIdAutoRetargetDeleteRaw(requestParameters: PublicBroadcastsIdAutoRetargetDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Cancel an automatic retarget
     */
    publicBroadcastsIdAutoRetargetDelete(requestParameters: PublicBroadcastsIdAutoRetargetDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for publicBroadcastsIdAutoRetargetGet without sending the request
     * @param {string} id Broadcast id (GraphQL broadcasts query)
     * @throws {RequiredError}
     * @memberof BroadcastsApiInterface
     */
    publicBroadcastsIdAutoRetargetGetRequestOpts(requestParameters: PublicBroadcastsIdAutoRetargetGetRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get a broadcast\'s automatic retarget
     * @param {string} id Broadcast id (GraphQL broadcasts query)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BroadcastsApiInterface
     */
    publicBroadcastsIdAutoRetargetGetRaw(requestParameters: PublicBroadcastsIdAutoRetargetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Get a broadcast\'s automatic retarget
     */
    publicBroadcastsIdAutoRetargetGet(requestParameters: PublicBroadcastsIdAutoRetargetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for publicBroadcastsIdAutoRetargetPost without sending the request
     * @param {string} id Broadcast id
     * @param {object} body { delay_hours, consent_attested: true, template_id?, template_params? }
     * @throws {RequiredError}
     * @memberof BroadcastsApiInterface
     */
    publicBroadcastsIdAutoRetargetPostRequestOpts(requestParameters: PublicBroadcastsIdAutoRetargetPostRequest): Promise<runtime.RequestOpts>;

    /**
     * After delay_hours (1 to 72), sends a follow-up to the people who got the broadcast but did not read it. Same template unless template_id is given (WhatsApp only), with template_params as a JSON string of its components. Charged like any broadcast when it sends.
     * @summary Schedule an automatic retarget
     * @param {string} id Broadcast id
     * @param {object} body { delay_hours, consent_attested: true, template_id?, template_params? }
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BroadcastsApiInterface
     */
    publicBroadcastsIdAutoRetargetPostRaw(requestParameters: PublicBroadcastsIdAutoRetargetPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * After delay_hours (1 to 72), sends a follow-up to the people who got the broadcast but did not read it. Same template unless template_id is given (WhatsApp only), with template_params as a JSON string of its components. Charged like any broadcast when it sends.
     * Schedule an automatic retarget
     */
    publicBroadcastsIdAutoRetargetPost(requestParameters: PublicBroadcastsIdAutoRetargetPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

}

/**
 * 
 */
export class BroadcastsApi extends runtime.BaseAPI implements BroadcastsApiInterface {

    /**
     * Creates request options for publicBroadcastsIdAutoRetargetDelete without sending the request
     */
    async publicBroadcastsIdAutoRetargetDeleteRequestOpts(requestParameters: PublicBroadcastsIdAutoRetargetDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling publicBroadcastsIdAutoRetargetDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/broadcasts/{id}/auto-retarget`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Cancel an automatic retarget
     */
    async publicBroadcastsIdAutoRetargetDeleteRaw(requestParameters: PublicBroadcastsIdAutoRetargetDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.publicBroadcastsIdAutoRetargetDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Cancel an automatic retarget
     */
    async publicBroadcastsIdAutoRetargetDelete(requestParameters: PublicBroadcastsIdAutoRetargetDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicBroadcastsIdAutoRetargetDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicBroadcastsIdAutoRetargetGet without sending the request
     */
    async publicBroadcastsIdAutoRetargetGetRequestOpts(requestParameters: PublicBroadcastsIdAutoRetargetGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling publicBroadcastsIdAutoRetargetGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/broadcasts/{id}/auto-retarget`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a broadcast\'s automatic retarget
     */
    async publicBroadcastsIdAutoRetargetGetRaw(requestParameters: PublicBroadcastsIdAutoRetargetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.publicBroadcastsIdAutoRetargetGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get a broadcast\'s automatic retarget
     */
    async publicBroadcastsIdAutoRetargetGet(requestParameters: PublicBroadcastsIdAutoRetargetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicBroadcastsIdAutoRetargetGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicBroadcastsIdAutoRetargetPost without sending the request
     */
    async publicBroadcastsIdAutoRetargetPostRequestOpts(requestParameters: PublicBroadcastsIdAutoRetargetPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling publicBroadcastsIdAutoRetargetPost().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling publicBroadcastsIdAutoRetargetPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/broadcasts/{id}/auto-retarget`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * After delay_hours (1 to 72), sends a follow-up to the people who got the broadcast but did not read it. Same template unless template_id is given (WhatsApp only), with template_params as a JSON string of its components. Charged like any broadcast when it sends.
     * Schedule an automatic retarget
     */
    async publicBroadcastsIdAutoRetargetPostRaw(requestParameters: PublicBroadcastsIdAutoRetargetPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.publicBroadcastsIdAutoRetargetPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * After delay_hours (1 to 72), sends a follow-up to the people who got the broadcast but did not read it. Same template unless template_id is given (WhatsApp only), with template_params as a JSON string of its components. Charged like any broadcast when it sends.
     * Schedule an automatic retarget
     */
    async publicBroadcastsIdAutoRetargetPost(requestParameters: PublicBroadcastsIdAutoRetargetPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicBroadcastsIdAutoRetargetPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
