/* tslint:disable */
/* eslint-disable */
/**
 * Splashify Pro API
 * REST endpoints for three product surfaces: 1. **Public API** under /public/_* — WhatsApp messaging, contacts, conversations, transactional email, Meta Conversions API. Authenticate with sk_live_… keys. 2. **Partner Email API** under /partner/email/_* — AWS-SES-shaped resold email platform: identities, configuration sets, templates, suppression, send, send-template, send-bulk, send-raw, quotas, stats, reputation, events. Authenticate with pk_live_… keys. 3. **App API** under /app/_* — the same surface the customer dashboard and the CLI/OpenClaw integrations use, authenticated with either an app session or an oc_live_… access token (`splashify auth login` / Settings → Developer → Access Tokens). Coverage here is partial — only endpoints touched by integrator reports are annotated so far, not the full surface. SDKs for Node.js, Python, and PHP are auto-generated from this spec.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@splashifypro.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
} from '../models/index';

export interface AppMessagesConversationsConversationIdAssignPostRequest {
    conversationId: string;
    body: object;
}

export interface PublicAssignmentPostRequest {
    body: object;
}

/**
 * ConversationsApi - interface
 * 
 * @export
 * @interface ConversationsApiInterface
 */
export interface ConversationsApiInterface {
    /**
     * Creates request options for appMessagesConversationsConversationIdAssignPost without sending the request
     * @param {string} conversationId Conversation ID
     * @param {object} body { assigned_to: string }, empty string releases
     * @throws {RequiredError}
     * @memberof ConversationsApiInterface
     */
    appMessagesConversationsConversationIdAssignPostRequestOpts(requestParameters: AppMessagesConversationsConversationIdAssignPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Assigns a conversation to a team member, or releases it when assigned_to is empty — fires team_member_assigned or team_member_unassigned respectively.
     * @summary Assign or release a conversation
     * @param {string} conversationId Conversation ID
     * @param {object} body { assigned_to: string }, empty string releases
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConversationsApiInterface
     */
    appMessagesConversationsConversationIdAssignPostRaw(requestParameters: AppMessagesConversationsConversationIdAssignPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Assigns a conversation to a team member, or releases it when assigned_to is empty — fires team_member_assigned or team_member_unassigned respectively.
     * Assign or release a conversation
     */
    appMessagesConversationsConversationIdAssignPost(requestParameters: AppMessagesConversationsConversationIdAssignPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for publicAssignmentPost without sending the request
     * @param {object} body Assignment payload: user_phone_number (required), agent_email (empty/omitted releases)
     * @throws {RequiredError}
     * @memberof ConversationsApiInterface
     */
    publicAssignmentPostRequestOpts(requestParameters: PublicAssignmentPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Routes a conversation to a specific team member by their email address, or releases it when agent_email is empty or omitted. Conversation is identified by the customer\'s phone number. Both agent and conversation must belong to the authenticated account.
     * @summary Assign or release a chat
     * @param {object} body Assignment payload: user_phone_number (required), agent_email (empty/omitted releases)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConversationsApiInterface
     */
    publicAssignmentPostRaw(requestParameters: PublicAssignmentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Routes a conversation to a specific team member by their email address, or releases it when agent_email is empty or omitted. Conversation is identified by the customer\'s phone number. Both agent and conversation must belong to the authenticated account.
     * Assign or release a chat
     */
    publicAssignmentPost(requestParameters: PublicAssignmentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

}

/**
 * 
 */
export class ConversationsApi extends runtime.BaseAPI implements ConversationsApiInterface {

    /**
     * Creates request options for appMessagesConversationsConversationIdAssignPost without sending the request
     */
    async appMessagesConversationsConversationIdAssignPostRequestOpts(requestParameters: AppMessagesConversationsConversationIdAssignPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling appMessagesConversationsConversationIdAssignPost().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling appMessagesConversationsConversationIdAssignPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/app/messages/conversations/{conversation_id}/assign`;
        urlPath = urlPath.replace('{conversation_id}', encodeURIComponent(String(requestParameters['conversationId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Assigns a conversation to a team member, or releases it when assigned_to is empty — fires team_member_assigned or team_member_unassigned respectively.
     * Assign or release a conversation
     */
    async appMessagesConversationsConversationIdAssignPostRaw(requestParameters: AppMessagesConversationsConversationIdAssignPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.appMessagesConversationsConversationIdAssignPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Assigns a conversation to a team member, or releases it when assigned_to is empty — fires team_member_assigned or team_member_unassigned respectively.
     * Assign or release a conversation
     */
    async appMessagesConversationsConversationIdAssignPost(requestParameters: AppMessagesConversationsConversationIdAssignPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.appMessagesConversationsConversationIdAssignPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicAssignmentPost without sending the request
     */
    async publicAssignmentPostRequestOpts(requestParameters: PublicAssignmentPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling publicAssignmentPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/assignment`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Routes a conversation to a specific team member by their email address, or releases it when agent_email is empty or omitted. Conversation is identified by the customer\'s phone number. Both agent and conversation must belong to the authenticated account.
     * Assign or release a chat
     */
    async publicAssignmentPostRaw(requestParameters: PublicAssignmentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.publicAssignmentPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Routes a conversation to a specific team member by their email address, or releases it when agent_email is empty or omitted. Conversation is identified by the customer\'s phone number. Both agent and conversation must belong to the authenticated account.
     * Assign or release a chat
     */
    async publicAssignmentPost(requestParameters: PublicAssignmentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicAssignmentPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
