/* tslint:disable */
/* eslint-disable */
/**
 * Splashify Pro API
 * REST endpoints for three product surfaces: 1. **Public API** under /public/_* — WhatsApp messaging, contacts, conversations, transactional email, Meta Conversions API. Authenticate with sk_live_… keys. 2. **Partner Email API** under /partner/email/_* — AWS-SES-shaped resold email platform: identities, configuration sets, templates, suppression, send, send-template, send-bulk, send-raw, quotas, stats, reputation, events. Authenticate with pk_live_… keys. 3. **App API** under /app/_* — the same surface the customer dashboard and the CLI/OpenClaw integrations use, authenticated with either an app session or an oc_live_… access token (`splashify auth login` / Settings → Developer → Access Tokens). Coverage here is partial — only endpoints touched by integrator reports are annotated so far, not the full surface. SDKs for Node.js, Python, and PHP are auto-generated from this spec.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@splashifypro.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    HandlersUpdateOptOutErrorRequest,
    HandlersUpdateWebhookRequest,
} from '../models/index';

export interface AppDeveloperOptOutErrorPutRequest {
    body: HandlersUpdateOptOutErrorRequest;
}

export interface AppDeveloperWebhookPutRequest {
    body: HandlersUpdateWebhookRequest;
}

/**
 * DeveloperApi - interface
 * 
 * @export
 * @interface DeveloperApiInterface
 */
export interface DeveloperApiInterface {
    /**
     * Creates request options for appDeveloperOptOutErrorPut without sending the request
     * @param {HandlersUpdateOptOutErrorRequest} body { enabled: boolean }
     * @throws {RequiredError}
     * @memberof DeveloperApiInterface
     */
    appDeveloperOptOutErrorPutRequestOpts(requestParameters: AppDeveloperOptOutErrorPutRequest): Promise<runtime.RequestOpts>;

    /**
     * When enabled, the Message Send API returns an error instead of silently no-op\'ing when called for a contact who has opted out.
     * @summary Toggle opt-out send errors
     * @param {HandlersUpdateOptOutErrorRequest} body { enabled: boolean }
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeveloperApiInterface
     */
    appDeveloperOptOutErrorPutRaw(requestParameters: AppDeveloperOptOutErrorPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * When enabled, the Message Send API returns an error instead of silently no-op\'ing when called for a contact who has opted out.
     * Toggle opt-out send errors
     */
    appDeveloperOptOutErrorPut(requestParameters: AppDeveloperOptOutErrorPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for appDeveloperSecretKeyGeneratePost without sending the request
     * @throws {RequiredError}
     * @memberof DeveloperApiInterface
     */
    appDeveloperSecretKeyGeneratePostRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * Invalidates any existing sk_live_ key immediately. This is the Authorization key for /api/v1/public/_* requests — a different secret from any webhook\'s signing secret.
     * @summary Generate (or regenerate) the API secret key
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeveloperApiInterface
     */
    appDeveloperSecretKeyGeneratePostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Invalidates any existing sk_live_ key immediately. This is the Authorization key for /api/v1/public/_* requests — a different secret from any webhook\'s signing secret.
     * Generate (or regenerate) the API secret key
     */
    appDeveloperSecretKeyGeneratePost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for appDeveloperSettingsGet without sending the request
     * @throws {RequiredError}
     * @memberof DeveloperApiInterface
     */
    appDeveloperSettingsGetRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * webhook_id/webhook_secret/webhook_active describe the real app_webhooks row backing this page\'s Configure Webhook editor — the same object GET /app/webhooks lists and POST /app/webhooks/{id}/rotate-secret operates on. Deliveries to webhook_url are signed with webhook_secret exactly like any webhook created through that API.
     * @summary Get developer settings
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeveloperApiInterface
     */
    appDeveloperSettingsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * webhook_id/webhook_secret/webhook_active describe the real app_webhooks row backing this page\'s Configure Webhook editor — the same object GET /app/webhooks lists and POST /app/webhooks/{id}/rotate-secret operates on. Deliveries to webhook_url are signed with webhook_secret exactly like any webhook created through that API.
     * Get developer settings
     */
    appDeveloperSettingsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for appDeveloperWebhookPut without sending the request
     * @param {HandlersUpdateWebhookRequest} body { webhook_url: string, webhook_events: string[] }
     * @throws {RequiredError}
     * @memberof DeveloperApiInterface
     */
    appDeveloperWebhookPutRequestOpts(requestParameters: AppDeveloperWebhookPutRequest): Promise<runtime.RequestOpts>;

    /**
     * Creates or updates the single app_webhooks row backing this page — its id and signing secret stay stable across edits, so changing the URL never invalidates signature verification. Deliveries are signed exactly like a webhook created via POST /app/webhooks (same headers, same HMAC scheme) — see Verifying signatures in the webhooks guide. An empty webhook_url deactivates it without deleting it; reconfiguring later reuses the same id and secret. Manage it like any other webhook via GET/PATCH/DELETE /app/webhooks/{id} and /rotate-secret using the webhook_id returned by GET /app/developer/settings.
     * @summary Configure the console webhook
     * @param {HandlersUpdateWebhookRequest} body { webhook_url: string, webhook_events: string[] }
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeveloperApiInterface
     */
    appDeveloperWebhookPutRaw(requestParameters: AppDeveloperWebhookPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Creates or updates the single app_webhooks row backing this page — its id and signing secret stay stable across edits, so changing the URL never invalidates signature verification. Deliveries are signed exactly like a webhook created via POST /app/webhooks (same headers, same HMAC scheme) — see Verifying signatures in the webhooks guide. An empty webhook_url deactivates it without deleting it; reconfiguring later reuses the same id and secret. Manage it like any other webhook via GET/PATCH/DELETE /app/webhooks/{id} and /rotate-secret using the webhook_id returned by GET /app/developer/settings.
     * Configure the console webhook
     */
    appDeveloperWebhookPut(requestParameters: AppDeveloperWebhookPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

}

/**
 * 
 */
export class DeveloperApi extends runtime.BaseAPI implements DeveloperApiInterface {

    /**
     * Creates request options for appDeveloperOptOutErrorPut without sending the request
     */
    async appDeveloperOptOutErrorPutRequestOpts(requestParameters: AppDeveloperOptOutErrorPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling appDeveloperOptOutErrorPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/app/developer/opt-out-error`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'],
        };
    }

    /**
     * When enabled, the Message Send API returns an error instead of silently no-op\'ing when called for a contact who has opted out.
     * Toggle opt-out send errors
     */
    async appDeveloperOptOutErrorPutRaw(requestParameters: AppDeveloperOptOutErrorPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.appDeveloperOptOutErrorPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * When enabled, the Message Send API returns an error instead of silently no-op\'ing when called for a contact who has opted out.
     * Toggle opt-out send errors
     */
    async appDeveloperOptOutErrorPut(requestParameters: AppDeveloperOptOutErrorPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.appDeveloperOptOutErrorPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for appDeveloperSecretKeyGeneratePost without sending the request
     */
    async appDeveloperSecretKeyGeneratePostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/app/developer/secret-key/generate`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Invalidates any existing sk_live_ key immediately. This is the Authorization key for /api/v1/public/_* requests — a different secret from any webhook\'s signing secret.
     * Generate (or regenerate) the API secret key
     */
    async appDeveloperSecretKeyGeneratePostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.appDeveloperSecretKeyGeneratePostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Invalidates any existing sk_live_ key immediately. This is the Authorization key for /api/v1/public/_* requests — a different secret from any webhook\'s signing secret.
     * Generate (or regenerate) the API secret key
     */
    async appDeveloperSecretKeyGeneratePost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.appDeveloperSecretKeyGeneratePostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for appDeveloperSettingsGet without sending the request
     */
    async appDeveloperSettingsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/app/developer/settings`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * webhook_id/webhook_secret/webhook_active describe the real app_webhooks row backing this page\'s Configure Webhook editor — the same object GET /app/webhooks lists and POST /app/webhooks/{id}/rotate-secret operates on. Deliveries to webhook_url are signed with webhook_secret exactly like any webhook created through that API.
     * Get developer settings
     */
    async appDeveloperSettingsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.appDeveloperSettingsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * webhook_id/webhook_secret/webhook_active describe the real app_webhooks row backing this page\'s Configure Webhook editor — the same object GET /app/webhooks lists and POST /app/webhooks/{id}/rotate-secret operates on. Deliveries to webhook_url are signed with webhook_secret exactly like any webhook created through that API.
     * Get developer settings
     */
    async appDeveloperSettingsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.appDeveloperSettingsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for appDeveloperWebhookPut without sending the request
     */
    async appDeveloperWebhookPutRequestOpts(requestParameters: AppDeveloperWebhookPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling appDeveloperWebhookPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/app/developer/webhook`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'],
        };
    }

    /**
     * Creates or updates the single app_webhooks row backing this page — its id and signing secret stay stable across edits, so changing the URL never invalidates signature verification. Deliveries are signed exactly like a webhook created via POST /app/webhooks (same headers, same HMAC scheme) — see Verifying signatures in the webhooks guide. An empty webhook_url deactivates it without deleting it; reconfiguring later reuses the same id and secret. Manage it like any other webhook via GET/PATCH/DELETE /app/webhooks/{id} and /rotate-secret using the webhook_id returned by GET /app/developer/settings.
     * Configure the console webhook
     */
    async appDeveloperWebhookPutRaw(requestParameters: AppDeveloperWebhookPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.appDeveloperWebhookPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Creates or updates the single app_webhooks row backing this page — its id and signing secret stay stable across edits, so changing the URL never invalidates signature verification. Deliveries are signed exactly like a webhook created via POST /app/webhooks (same headers, same HMAC scheme) — see Verifying signatures in the webhooks guide. An empty webhook_url deactivates it without deleting it; reconfiguring later reuses the same id and secret. Manage it like any other webhook via GET/PATCH/DELETE /app/webhooks/{id} and /rotate-secret using the webhook_id returned by GET /app/developer/settings.
     * Configure the console webhook
     */
    async appDeveloperWebhookPut(requestParameters: AppDeveloperWebhookPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.appDeveloperWebhookPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
