/* tslint:disable */
/* eslint-disable */
/**
 * Splashify Pro API
 * REST endpoints for three product surfaces: 1. **Public API** under /public/_* — WhatsApp messaging, contacts, conversations, transactional email, Meta Conversions API. Authenticate with sk_live_… keys. 2. **Partner Email API** under /partner/email/_* — AWS-SES-shaped resold email platform: identities, configuration sets, templates, suppression, send, send-template, send-bulk, send-raw, quotas, stats, reputation, events. Authenticate with pk_live_… keys. 3. **App API** under /app/_* — the same surface the customer dashboard and the CLI/OpenClaw integrations use, authenticated with either an app session or an oc_live_… access token (`splashify auth login` / Settings → Developer → Access Tokens). Coverage here is partial — only endpoints touched by integrator reports are annotated so far, not the full surface. SDKs for Node.js, Python, and PHP are auto-generated from this spec.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@splashifypro.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
} from '../models/index';

export interface PublicDripStartPostRequest {
    request: object;
}

/**
 * DripCampaignsApi - interface
 * 
 * @export
 * @interface DripCampaignsApiInterface
 */
export interface DripCampaignsApiInterface {
    /**
     * Creates request options for publicDripCampaignsGet without sending the request
     * @throws {RequiredError}
     * @memberof DripCampaignsApiInterface
     */
    publicDripCampaignsGetRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * Returns this account\'s drip campaigns with their id, name and status. Use the campaign_id with the start endpoint.
     * @summary List drip campaigns
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DripCampaignsApiInterface
     */
    publicDripCampaignsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Returns this account\'s drip campaigns with their id, name and status. Use the campaign_id with the start endpoint.
     * List drip campaigns
     */
    publicDripCampaignsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for publicDripStartPost without sending the request
     * @param {object} request campaign_id and phone_number
     * @throws {RequiredError}
     * @memberof DripCampaignsApiInterface
     */
    publicDripStartPostRequestOpts(requestParameters: PublicDripStartPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Enrols one contact into a drip campaign. The first message goes out after that step\'s configured wait, and the rest follow on their own schedule. The campaign must be running. Safe to call twice — a contact already in the campaign is reported, not enrolled again.
     * @summary Start a drip campaign for a contact
     * @param {object} request campaign_id and phone_number
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DripCampaignsApiInterface
     */
    publicDripStartPostRaw(requestParameters: PublicDripStartPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Enrols one contact into a drip campaign. The first message goes out after that step\'s configured wait, and the rest follow on their own schedule. The campaign must be running. Safe to call twice — a contact already in the campaign is reported, not enrolled again.
     * Start a drip campaign for a contact
     */
    publicDripStartPost(requestParameters: PublicDripStartPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

}

/**
 * 
 */
export class DripCampaignsApi extends runtime.BaseAPI implements DripCampaignsApiInterface {

    /**
     * Creates request options for publicDripCampaignsGet without sending the request
     */
    async publicDripCampaignsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/public/drip/campaigns`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns this account\'s drip campaigns with their id, name and status. Use the campaign_id with the start endpoint.
     * List drip campaigns
     */
    async publicDripCampaignsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.publicDripCampaignsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Returns this account\'s drip campaigns with their id, name and status. Use the campaign_id with the start endpoint.
     * List drip campaigns
     */
    async publicDripCampaignsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicDripCampaignsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicDripStartPost without sending the request
     */
    async publicDripStartPostRequestOpts(requestParameters: PublicDripStartPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling publicDripStartPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/public/drip/start`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['request'] as any,
        };
    }

    /**
     * Enrols one contact into a drip campaign. The first message goes out after that step\'s configured wait, and the rest follow on their own schedule. The campaign must be running. Safe to call twice — a contact already in the campaign is reported, not enrolled again.
     * Start a drip campaign for a contact
     */
    async publicDripStartPostRaw(requestParameters: PublicDripStartPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.publicDripStartPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Enrols one contact into a drip campaign. The first message goes out after that step\'s configured wait, and the rest follow on their own schedule. The campaign must be running. Safe to call twice — a contact already in the campaign is reported, not enrolled again.
     * Start a drip campaign for a contact
     */
    async publicDripStartPost(requestParameters: PublicDripStartPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicDripStartPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
