/* tslint:disable */
/* eslint-disable */
/**
 * Splashify Pro API
 * REST endpoints for three product surfaces: 1. **Public API** under /public/_* — WhatsApp messaging, contacts, conversations, transactional email, Meta Conversions API. Authenticate with sk_live_… keys. 2. **Partner Email API** under /partner/email/_* — AWS-SES-shaped resold email platform: identities, configuration sets, templates, suppression, send, send-template, send-bulk, send-raw, quotas, stats, reputation, events. Authenticate with pk_live_… keys. 3. **App API** under /app/_* — the same surface the customer dashboard and the CLI/OpenClaw integrations use, authenticated with either an app session or an oc_live_… access token (`splashify auth login` / Settings → Developer → Access Tokens). Coverage here is partial — only endpoints touched by integrator reports are annotated so far, not the full surface. SDKs for Node.js, Python, and PHP are auto-generated from this spec.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@splashifypro.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
} from '../models/index';

export interface PublicEmailSendPostRequest {
    body: object;
}

export interface PublicEmailSendTemplatePostRequest {
    body: object;
}

export interface PublicEmailStatusMessageIdGetRequest {
    messageId: string;
}

/**
 * EmailApi - interface
 * 
 * @export
 * @interface EmailApiInterface
 */
export interface EmailApiInterface {
    /**
     * Creates request options for publicEmailSendPost without sending the request
     * @param {object} body Send email payload (to, subject, html, text, from_email, reply_to, attachments)
     * @throws {RequiredError}
     * @memberof EmailApiInterface
     */
    publicEmailSendPostRequestOpts(requestParameters: PublicEmailSendPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Send a fully-formed HTML email to one or more recipients. Caller supplies subject + html + text + from_email + recipient. Optional attachments[] (PDFs, images, docs) ride inline as base64 — backend builds multipart/mixed and DKIM-signs. Caps: 20 files / 10 MiB total / executable extensions blocked. Delivered via the platform\'s self-hosted email pipeline with category=email_transactional. From-email must be on a verified sender domain.
     * @summary Send a transactional email
     * @param {object} body Send email payload (to, subject, html, text, from_email, reply_to, attachments)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmailApiInterface
     */
    publicEmailSendPostRaw(requestParameters: PublicEmailSendPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Send a fully-formed HTML email to one or more recipients. Caller supplies subject + html + text + from_email + recipient. Optional attachments[] (PDFs, images, docs) ride inline as base64 — backend builds multipart/mixed and DKIM-signs. Caps: 20 files / 10 MiB total / executable extensions blocked. Delivered via the platform\'s self-hosted email pipeline with category=email_transactional. From-email must be on a verified sender domain.
     * Send a transactional email
     */
    publicEmailSendPost(requestParameters: PublicEmailSendPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for publicEmailSendTemplatePost without sending the request
     * @param {object} body Template send payload (to, template_id, variables, from_email, subject, attachments)
     * @throws {RequiredError}
     * @memberof EmailApiInterface
     */
    publicEmailSendTemplatePostRequestOpts(requestParameters: PublicEmailSendTemplatePostRequest): Promise<runtime.RequestOpts>;

    /**
     * Send an email using a saved template (created via the in-app template editor at /email/templates). Caller supplies template_id + recipient + variables map. Backend pulls the template\'s pre-rendered HTML and substitutes {{vars}}. Optional attachments[] ride inline as base64 — same shape + caps as /send (20 files / 10 MiB / blocked extensions).
     * @summary Send a templated email
     * @param {object} body Template send payload (to, template_id, variables, from_email, subject, attachments)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmailApiInterface
     */
    publicEmailSendTemplatePostRaw(requestParameters: PublicEmailSendTemplatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Send an email using a saved template (created via the in-app template editor at /email/templates). Caller supplies template_id + recipient + variables map. Backend pulls the template\'s pre-rendered HTML and substitutes {{vars}}. Optional attachments[] ride inline as base64 — same shape + caps as /send (20 files / 10 MiB / blocked extensions).
     * Send a templated email
     */
    publicEmailSendTemplatePost(requestParameters: PublicEmailSendTemplatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for publicEmailStatusMessageIdGet without sending the request
     * @param {string} messageId Message ID returned by send
     * @throws {RequiredError}
     * @memberof EmailApiInterface
     */
    publicEmailStatusMessageIdGetRequestOpts(requestParameters: PublicEmailStatusMessageIdGetRequest): Promise<runtime.RequestOpts>;

    /**
     * Look up the current status of an email message by its message_id (returned from /public/email/send or /send-template). Status values: queued, sending, delivered, bounced, failed.
     * @summary Get email delivery status
     * @param {string} messageId Message ID returned by send
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmailApiInterface
     */
    publicEmailStatusMessageIdGetRaw(requestParameters: PublicEmailStatusMessageIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Look up the current status of an email message by its message_id (returned from /public/email/send or /send-template). Status values: queued, sending, delivered, bounced, failed.
     * Get email delivery status
     */
    publicEmailStatusMessageIdGet(requestParameters: PublicEmailStatusMessageIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

}

/**
 * 
 */
export class EmailApi extends runtime.BaseAPI implements EmailApiInterface {

    /**
     * Creates request options for publicEmailSendPost without sending the request
     */
    async publicEmailSendPostRequestOpts(requestParameters: PublicEmailSendPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling publicEmailSendPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/email/send`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Send a fully-formed HTML email to one or more recipients. Caller supplies subject + html + text + from_email + recipient. Optional attachments[] (PDFs, images, docs) ride inline as base64 — backend builds multipart/mixed and DKIM-signs. Caps: 20 files / 10 MiB total / executable extensions blocked. Delivered via the platform\'s self-hosted email pipeline with category=email_transactional. From-email must be on a verified sender domain.
     * Send a transactional email
     */
    async publicEmailSendPostRaw(requestParameters: PublicEmailSendPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.publicEmailSendPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Send a fully-formed HTML email to one or more recipients. Caller supplies subject + html + text + from_email + recipient. Optional attachments[] (PDFs, images, docs) ride inline as base64 — backend builds multipart/mixed and DKIM-signs. Caps: 20 files / 10 MiB total / executable extensions blocked. Delivered via the platform\'s self-hosted email pipeline with category=email_transactional. From-email must be on a verified sender domain.
     * Send a transactional email
     */
    async publicEmailSendPost(requestParameters: PublicEmailSendPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicEmailSendPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicEmailSendTemplatePost without sending the request
     */
    async publicEmailSendTemplatePostRequestOpts(requestParameters: PublicEmailSendTemplatePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling publicEmailSendTemplatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/email/send-template`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Send an email using a saved template (created via the in-app template editor at /email/templates). Caller supplies template_id + recipient + variables map. Backend pulls the template\'s pre-rendered HTML and substitutes {{vars}}. Optional attachments[] ride inline as base64 — same shape + caps as /send (20 files / 10 MiB / blocked extensions).
     * Send a templated email
     */
    async publicEmailSendTemplatePostRaw(requestParameters: PublicEmailSendTemplatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.publicEmailSendTemplatePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Send an email using a saved template (created via the in-app template editor at /email/templates). Caller supplies template_id + recipient + variables map. Backend pulls the template\'s pre-rendered HTML and substitutes {{vars}}. Optional attachments[] ride inline as base64 — same shape + caps as /send (20 files / 10 MiB / blocked extensions).
     * Send a templated email
     */
    async publicEmailSendTemplatePost(requestParameters: PublicEmailSendTemplatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicEmailSendTemplatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicEmailStatusMessageIdGet without sending the request
     */
    async publicEmailStatusMessageIdGetRequestOpts(requestParameters: PublicEmailStatusMessageIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['messageId'] == null) {
            throw new runtime.RequiredError(
                'messageId',
                'Required parameter "messageId" was null or undefined when calling publicEmailStatusMessageIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/email/status/{message_id}`;
        urlPath = urlPath.replace('{message_id}', encodeURIComponent(String(requestParameters['messageId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Look up the current status of an email message by its message_id (returned from /public/email/send or /send-template). Status values: queued, sending, delivered, bounced, failed.
     * Get email delivery status
     */
    async publicEmailStatusMessageIdGetRaw(requestParameters: PublicEmailStatusMessageIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.publicEmailStatusMessageIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Look up the current status of an email message by its message_id (returned from /public/email/send or /send-template). Status values: queued, sending, delivered, bounced, failed.
     * Get email delivery status
     */
    async publicEmailStatusMessageIdGet(requestParameters: PublicEmailStatusMessageIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicEmailStatusMessageIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
