/* tslint:disable */
/* eslint-disable */
/**
 * Splashify Pro API
 * REST endpoints for three product surfaces: 1. **Public API** under /public/_* — WhatsApp messaging, contacts, conversations, transactional email, Meta Conversions API. Authenticate with sk_live_… keys. 2. **Partner Email API** under /partner/email/_* — AWS-SES-shaped resold email platform: identities, configuration sets, templates, suppression, send, send-template, send-bulk, send-raw, quotas, stats, reputation, events. Authenticate with pk_live_… keys. 3. **App API** under /app/_* — the same surface the customer dashboard and the CLI/OpenClaw integrations use, authenticated with either an app session or an oc_live_… access token (`splashify auth login` / Settings → Developer → Access Tokens). Coverage here is partial — only endpoints touched by integrator reports are annotated so far, not the full surface. SDKs for Node.js, Python, and PHP are auto-generated from this spec.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@splashifypro.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
} from '../models/index';

export interface AppExpensesBillingLogsGetRequest {
    period?: string;
    limit?: number;
    cursor?: string;
}

export interface AppExpensesSummaryGetRequest {
    period?: string;
}

/**
 * ExpensesApi - interface
 * 
 * @export
 * @interface ExpensesApiInterface
 */
export interface ExpensesApiInterface {
    /**
     * Creates request options for appExpensesBillingLogsGet without sending the request
     * @param {string} [period] 7d, 30d, 3m, 6m, or all — default 30d
     * @param {number} [limit] Page size, default 100, max 500
     * @param {string} [cursor] Opaque cursor from a previous response\&#39;s next_cursor
     * @throws {RequiredError}
     * @memberof ExpensesApiInterface
     */
    appExpensesBillingLogsGetRequestOpts(requestParameters: AppExpensesBillingLogsGetRequest): Promise<runtime.RequestOpts>;

    /**
     * Paginated per-message deduction log. total is a real count of billable rows for the period, not the size of one page; page with cursor/next_cursor.
     * @summary Billing log entries
     * @param {string} [period] 7d, 30d, 3m, 6m, or all — default 30d
     * @param {number} [limit] Page size, default 100, max 500
     * @param {string} [cursor] Opaque cursor from a previous response\&#39;s next_cursor
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExpensesApiInterface
     */
    appExpensesBillingLogsGetRaw(requestParameters: AppExpensesBillingLogsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Paginated per-message deduction log. total is a real count of billable rows for the period, not the size of one page; page with cursor/next_cursor.
     * Billing log entries
     */
    appExpensesBillingLogsGet(requestParameters: AppExpensesBillingLogsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for appExpensesSummaryGet without sending the request
     * @param {string} [period] 7d, 30d, 3m, 6m, or all — default 30d
     * @throws {RequiredError}
     * @memberof ExpensesApiInterface
     */
    appExpensesSummaryGetRequestOpts(requestParameters: AppExpensesSummaryGetRequest): Promise<runtime.RequestOpts>;

    /**
     * Message deduction stats: total spent, breakdown by category, total messages, and real sent/delivered counts from WhatsApp status (not the account\'s billing-timing preference). period in the response is the resolved value, not the raw query param — an unrecognised value silently falls back to 30d.
     * @summary Expense summary
     * @param {string} [period] 7d, 30d, 3m, 6m, or all — default 30d
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExpensesApiInterface
     */
    appExpensesSummaryGetRaw(requestParameters: AppExpensesSummaryGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Message deduction stats: total spent, breakdown by category, total messages, and real sent/delivered counts from WhatsApp status (not the account\'s billing-timing preference). period in the response is the resolved value, not the raw query param — an unrecognised value silently falls back to 30d.
     * Expense summary
     */
    appExpensesSummaryGet(requestParameters: AppExpensesSummaryGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

}

/**
 * 
 */
export class ExpensesApi extends runtime.BaseAPI implements ExpensesApiInterface {

    /**
     * Creates request options for appExpensesBillingLogsGet without sending the request
     */
    async appExpensesBillingLogsGetRequestOpts(requestParameters: AppExpensesBillingLogsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['period'] != null) {
            queryParameters['period'] = requestParameters['period'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/app/expenses/billing-logs`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Paginated per-message deduction log. total is a real count of billable rows for the period, not the size of one page; page with cursor/next_cursor.
     * Billing log entries
     */
    async appExpensesBillingLogsGetRaw(requestParameters: AppExpensesBillingLogsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.appExpensesBillingLogsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Paginated per-message deduction log. total is a real count of billable rows for the period, not the size of one page; page with cursor/next_cursor.
     * Billing log entries
     */
    async appExpensesBillingLogsGet(requestParameters: AppExpensesBillingLogsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.appExpensesBillingLogsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for appExpensesSummaryGet without sending the request
     */
    async appExpensesSummaryGetRequestOpts(requestParameters: AppExpensesSummaryGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['period'] != null) {
            queryParameters['period'] = requestParameters['period'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/app/expenses/summary`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Message deduction stats: total spent, breakdown by category, total messages, and real sent/delivered counts from WhatsApp status (not the account\'s billing-timing preference). period in the response is the resolved value, not the raw query param — an unrecognised value silently falls back to 30d.
     * Expense summary
     */
    async appExpensesSummaryGetRaw(requestParameters: AppExpensesSummaryGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.appExpensesSummaryGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Message deduction stats: total spent, breakdown by category, total messages, and real sent/delivered counts from WhatsApp status (not the account\'s billing-timing preference). period in the response is the resolved value, not the raw query param — an unrecognised value silently falls back to 30d.
     * Expense summary
     */
    async appExpensesSummaryGet(requestParameters: AppExpensesSummaryGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.appExpensesSummaryGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
