/* tslint:disable */
/* eslint-disable */
/**
 * Splashify Pro API
 * REST endpoints for three product surfaces: 1. **Public API** under /public/_* — WhatsApp messaging, contacts, conversations, transactional email, Meta Conversions API. Authenticate with sk_live_… keys. 2. **Partner Email API** under /partner/email/_* — AWS-SES-shaped resold email platform: identities, configuration sets, templates, suppression, send, send-template, send-bulk, send-raw, quotas, stats, reputation, events. Authenticate with pk_live_… keys. 3. **App API** under /app/_* — the same surface the customer dashboard and the CLI/OpenClaw integrations use, authenticated with either an app session or an oc_live_… access token (`splashify auth login` / Settings → Developer → Access Tokens). Coverage here is partial — only endpoints touched by integrator reports are annotated so far, not the full surface. SDKs for Node.js, Python, and PHP are auto-generated from this spec.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@splashifypro.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
} from '../models/index';

export interface AppMediaGetRequest {
    type?: string;
}

/**
 * MediaApi - interface
 * 
 * @export
 * @interface MediaApiInterface
 */
export interface MediaApiInterface {
    /**
     * Creates request options for appMediaGet without sending the request
     * @param {string} [type] Filter: image, video, audio, or document
     * @throws {RequiredError}
     * @memberof MediaApiInterface
     */
    appMediaGetRequestOpts(requestParameters: AppMediaGetRequest): Promise<runtime.RequestOpts>;

    /**
     * storage_used/storage_limit are included so a caller does not need a second round-trip to GET /app/media/storage.
     * @summary List uploaded media files
     * @param {string} [type] Filter: image, video, audio, or document
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MediaApiInterface
     */
    appMediaGetRaw(requestParameters: AppMediaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * storage_used/storage_limit are included so a caller does not need a second round-trip to GET /app/media/storage.
     * List uploaded media files
     */
    appMediaGet(requestParameters: AppMediaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

}

/**
 * 
 */
export class MediaApi extends runtime.BaseAPI implements MediaApiInterface {

    /**
     * Creates request options for appMediaGet without sending the request
     */
    async appMediaGetRequestOpts(requestParameters: AppMediaGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/app/media`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * storage_used/storage_limit are included so a caller does not need a second round-trip to GET /app/media/storage.
     * List uploaded media files
     */
    async appMediaGetRaw(requestParameters: AppMediaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.appMediaGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * storage_used/storage_limit are included so a caller does not need a second round-trip to GET /app/media/storage.
     * List uploaded media files
     */
    async appMediaGet(requestParameters: AppMediaGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.appMediaGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
