/* tslint:disable */
/* eslint-disable */
/**
 * Splashify Pro API
 * REST endpoints for three product surfaces: 1. **Public API** under /public/_* — WhatsApp messaging, contacts, conversations, transactional email, Meta Conversions API. Authenticate with sk_live_… keys. 2. **Partner Email API** under /partner/email/_* — AWS-SES-shaped resold email platform: identities, configuration sets, templates, suppression, send, send-template, send-bulk, send-raw, quotas, stats, reputation, events. Authenticate with pk_live_… keys. 3. **App API** under /app/_* — the same surface the customer dashboard and the CLI/OpenClaw integrations use, authenticated with either an app session or an oc_live_… access token (`splashify auth login` / Settings → Developer → Access Tokens). Coverage here is partial — only endpoints touched by integrator reports are annotated so far, not the full surface. SDKs for Node.js, Python, and PHP are auto-generated from this spec.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@splashifypro.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
} from '../models/index';

export interface AppMessagesSendMediaPostRequest {
    body: object;
}

export interface AppMessagesTypingIndicatorPostRequest {
    body: object;
}

export interface PublicMessagePostRequest {
    body: object;
}

/**
 * MessagesApi - interface
 * 
 * @export
 * @interface MessagesApiInterface
 */
export interface MessagesApiInterface {
    /**
     * Creates request options for appMessagesSendMediaPost without sending the request
     * @param {object} body { to, media_type, media_url|media_id, caption?, filename?, voice? }
     * @throws {RequiredError}
     * @memberof MessagesApiInterface
     */
    appMessagesSendMediaPostRequestOpts(requestParameters: AppMessagesSendMediaPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Sends an image, video, audio, or document message. Pass either media_url (any public URL) or media_id (a file previously uploaded via POST /app/media) — not both required.
     * @summary Send a media message
     * @param {object} body { to, media_type, media_url|media_id, caption?, filename?, voice? }
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagesApiInterface
     */
    appMessagesSendMediaPostRaw(requestParameters: AppMessagesSendMediaPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Sends an image, video, audio, or document message. Pass either media_url (any public URL) or media_id (a file previously uploaded via POST /app/media) — not both required.
     * Send a media message
     */
    appMessagesSendMediaPost(requestParameters: AppMessagesSendMediaPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for appMessagesTypingIndicatorPost without sending the request
     * @param {object} body { message_id: string }
     * @throws {RequiredError}
     * @memberof MessagesApiInterface
     */
    appMessagesTypingIndicatorPostRequestOpts(requestParameters: AppMessagesTypingIndicatorPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Shows the typing indicator on the given inbound message\'s conversation. WhatsApp dismisses it after ~25s or on the next message from this business, whichever comes first.
     * @summary Send a typing indicator
     * @param {object} body { message_id: string }
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagesApiInterface
     */
    appMessagesTypingIndicatorPostRaw(requestParameters: AppMessagesTypingIndicatorPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Shows the typing indicator on the given inbound message\'s conversation. WhatsApp dismisses it after ~25s or on the next message from this business, whichever comes first.
     * Send a typing indicator
     */
    appMessagesTypingIndicatorPost(requestParameters: AppMessagesTypingIndicatorPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for publicMessagePost without sending the request
     * @param {object} body Send message payload (type, phoneNumber, data)
     * @throws {RequiredError}
     * @memberof MessagesApiInterface
     */
    publicMessagePostRequestOpts(requestParameters: PublicMessagePostRequest): Promise<runtime.RequestOpts>;

    /**
     * Send any supported WhatsApp message type to a contact. See type-specific request examples in the per-message docs.
     * @summary Send a WhatsApp message
     * @param {object} body Send message payload (type, phoneNumber, data)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagesApiInterface
     */
    publicMessagePostRaw(requestParameters: PublicMessagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Send any supported WhatsApp message type to a contact. See type-specific request examples in the per-message docs.
     * Send a WhatsApp message
     */
    publicMessagePost(requestParameters: PublicMessagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

}

/**
 * 
 */
export class MessagesApi extends runtime.BaseAPI implements MessagesApiInterface {

    /**
     * Creates request options for appMessagesSendMediaPost without sending the request
     */
    async appMessagesSendMediaPostRequestOpts(requestParameters: AppMessagesSendMediaPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling appMessagesSendMediaPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/app/messages/send-media`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Sends an image, video, audio, or document message. Pass either media_url (any public URL) or media_id (a file previously uploaded via POST /app/media) — not both required.
     * Send a media message
     */
    async appMessagesSendMediaPostRaw(requestParameters: AppMessagesSendMediaPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.appMessagesSendMediaPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Sends an image, video, audio, or document message. Pass either media_url (any public URL) or media_id (a file previously uploaded via POST /app/media) — not both required.
     * Send a media message
     */
    async appMessagesSendMediaPost(requestParameters: AppMessagesSendMediaPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.appMessagesSendMediaPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for appMessagesTypingIndicatorPost without sending the request
     */
    async appMessagesTypingIndicatorPostRequestOpts(requestParameters: AppMessagesTypingIndicatorPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling appMessagesTypingIndicatorPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/app/messages/typing-indicator`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Shows the typing indicator on the given inbound message\'s conversation. WhatsApp dismisses it after ~25s or on the next message from this business, whichever comes first.
     * Send a typing indicator
     */
    async appMessagesTypingIndicatorPostRaw(requestParameters: AppMessagesTypingIndicatorPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.appMessagesTypingIndicatorPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Shows the typing indicator on the given inbound message\'s conversation. WhatsApp dismisses it after ~25s or on the next message from this business, whichever comes first.
     * Send a typing indicator
     */
    async appMessagesTypingIndicatorPost(requestParameters: AppMessagesTypingIndicatorPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.appMessagesTypingIndicatorPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicMessagePost without sending the request
     */
    async publicMessagePostRequestOpts(requestParameters: PublicMessagePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling publicMessagePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/message`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Send any supported WhatsApp message type to a contact. See type-specific request examples in the per-message docs.
     * Send a WhatsApp message
     */
    async publicMessagePostRaw(requestParameters: PublicMessagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.publicMessagePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Send any supported WhatsApp message type to a contact. See type-specific request examples in the per-message docs.
     * Send a WhatsApp message
     */
    async publicMessagePost(requestParameters: PublicMessagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicMessagePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
