/* tslint:disable */
/* eslint-disable */
/**
 * Splashify Pro API
 * REST endpoints for three product surfaces: 1. **Public API** under /public/_* — WhatsApp messaging, contacts, conversations, transactional email, Meta Conversions API. Authenticate with sk_live_… keys. 2. **Partner Email API** under /partner/email/_* — AWS-SES-shaped resold email platform: identities, configuration sets, templates, suppression, send, send-template, send-bulk, send-raw, quotas, stats, reputation, events. Authenticate with pk_live_… keys. 3. **App API** under /app/_* — the same surface the customer dashboard and the CLI/OpenClaw integrations use, authenticated with either an app session or an oc_live_… access token (`splashify auth login` / Settings → Developer → Access Tokens). Coverage here is partial — only endpoints touched by integrator reports are annotated so far, not the full surface. SDKs for Node.js, Python, and PHP are auto-generated from this spec.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@splashifypro.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
} from '../models/index';

export interface PartnerEmailEmailsMessageIdGetRequest {
    messageId: string;
}

export interface PartnerEmailSendBulkPostRequest {
    body: object;
}

export interface PartnerEmailSendPostRequest {
    body: object;
}

export interface PartnerEmailSendRawPostRequest {
    body: object;
}

export interface PartnerEmailSendTemplatePostRequest {
    body: object;
}

/**
 * PartnerEmailSendApi - interface
 * 
 * @export
 * @interface PartnerEmailSendApiInterface
 */
export interface PartnerEmailSendApiInterface {
    /**
     * Creates request options for partnerEmailEmailsMessageIdGet without sending the request
     * @param {string} messageId Message ID returned from /send
     * @throws {RequiredError}
     * @memberof PartnerEmailSendApiInterface
     */
    partnerEmailEmailsMessageIdGetRequestOpts(requestParameters: PartnerEmailEmailsMessageIdGetRequest): Promise<runtime.RequestOpts>;

    /**
     * Look up the current status and event timeline for an email by message_id. Returns sent / delivered / bounced / complained state plus open + click counters.
     * @summary Get email status
     * @param {string} messageId Message ID returned from /send
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnerEmailSendApiInterface
     */
    partnerEmailEmailsMessageIdGetRaw(requestParameters: PartnerEmailEmailsMessageIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Look up the current status and event timeline for an email by message_id. Returns sent / delivered / bounced / complained state plus open + click counters.
     * Get email status
     */
    partnerEmailEmailsMessageIdGet(requestParameters: PartnerEmailEmailsMessageIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for partnerEmailSendBulkPost without sending the request
     * @param {object} body Send bulk payload (template_name, from, default_template_data, destinations[])
     * @throws {RequiredError}
     * @memberof PartnerEmailSendApiInterface
     */
    partnerEmailSendBulkPostRequestOpts(requestParameters: PartnerEmailSendBulkPostRequest): Promise<runtime.RequestOpts>;

    /**
     * One template + one verified From + N destinations, each with its own ReplacementData map. Equivalent to AWS SES SendBulkTemplatedEmail. Caps: 50 destinations × 50 recipients = 500 total per request.
     * @summary Send bulk templated email
     * @param {object} body Send bulk payload (template_name, from, default_template_data, destinations[])
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnerEmailSendApiInterface
     */
    partnerEmailSendBulkPostRaw(requestParameters: PartnerEmailSendBulkPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * One template + one verified From + N destinations, each with its own ReplacementData map. Equivalent to AWS SES SendBulkTemplatedEmail. Caps: 50 destinations × 50 recipients = 500 total per request.
     * Send bulk templated email
     */
    partnerEmailSendBulkPost(requestParameters: PartnerEmailSendBulkPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for partnerEmailSendPost without sending the request
     * @param {object} body Send email payload (from, to, subject, html_body, text_body, configuration_set_name?)
     * @throws {RequiredError}
     * @memberof PartnerEmailSendApiInterface
     */
    partnerEmailSendPostRequestOpts(requestParameters: PartnerEmailSendPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Send a transactional or marketing email to up to 50 recipients (combined to + cc + bcc). Equivalent to AWS SES SendEmail.
     * @summary Send email
     * @param {object} body Send email payload (from, to, subject, html_body, text_body, configuration_set_name?)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnerEmailSendApiInterface
     */
    partnerEmailSendPostRaw(requestParameters: PartnerEmailSendPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Send a transactional or marketing email to up to 50 recipients (combined to + cc + bcc). Equivalent to AWS SES SendEmail.
     * Send email
     */
    partnerEmailSendPost(requestParameters: PartnerEmailSendPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for partnerEmailSendRawPost without sending the request
     * @param {object} body Send raw payload (raw_message_base64, destinations[], from, configuration_set_name?)
     * @throws {RequiredError}
     * @memberof PartnerEmailSendApiInterface
     */
    partnerEmailSendRawPostRequestOpts(requestParameters: PartnerEmailSendRawPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Submit a pre-built RFC 5322 MIME message — useful when you\'ve already constructed the email body yourself (DKIM-ready, multipart, calendar invites, etc). Equivalent to AWS SES SendRawEmail. Max 10 MiB raw body.
     * @summary Send raw MIME email
     * @param {object} body Send raw payload (raw_message_base64, destinations[], from, configuration_set_name?)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnerEmailSendApiInterface
     */
    partnerEmailSendRawPostRaw(requestParameters: PartnerEmailSendRawPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Submit a pre-built RFC 5322 MIME message — useful when you\'ve already constructed the email body yourself (DKIM-ready, multipart, calendar invites, etc). Equivalent to AWS SES SendRawEmail. Max 10 MiB raw body.
     * Send raw MIME email
     */
    partnerEmailSendRawPost(requestParameters: PartnerEmailSendRawPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for partnerEmailSendTemplatePost without sending the request
     * @param {object} body Send template payload (template_name OR template_id, from, to[], variables{})
     * @throws {RequiredError}
     * @memberof PartnerEmailSendApiInterface
     */
    partnerEmailSendTemplatePostRequestOpts(requestParameters: PartnerEmailSendTemplatePostRequest): Promise<runtime.RequestOpts>;

    /**
     * Render a saved template with per-recipient variables and send it. Equivalent to AWS SES SendTemplatedEmail. Templates are pre-rendered at save time so per-send substitution is cheap.
     * @summary Send templated email
     * @param {object} body Send template payload (template_name OR template_id, from, to[], variables{})
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnerEmailSendApiInterface
     */
    partnerEmailSendTemplatePostRaw(requestParameters: PartnerEmailSendTemplatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Render a saved template with per-recipient variables and send it. Equivalent to AWS SES SendTemplatedEmail. Templates are pre-rendered at save time so per-send substitution is cheap.
     * Send templated email
     */
    partnerEmailSendTemplatePost(requestParameters: PartnerEmailSendTemplatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

}

/**
 * 
 */
export class PartnerEmailSendApi extends runtime.BaseAPI implements PartnerEmailSendApiInterface {

    /**
     * Creates request options for partnerEmailEmailsMessageIdGet without sending the request
     */
    async partnerEmailEmailsMessageIdGetRequestOpts(requestParameters: PartnerEmailEmailsMessageIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['messageId'] == null) {
            throw new runtime.RequiredError(
                'messageId',
                'Required parameter "messageId" was null or undefined when calling partnerEmailEmailsMessageIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/partner/email/emails/{message_id}`;
        urlPath = urlPath.replace('{message_id}', encodeURIComponent(String(requestParameters['messageId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Look up the current status and event timeline for an email by message_id. Returns sent / delivered / bounced / complained state plus open + click counters.
     * Get email status
     */
    async partnerEmailEmailsMessageIdGetRaw(requestParameters: PartnerEmailEmailsMessageIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.partnerEmailEmailsMessageIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Look up the current status and event timeline for an email by message_id. Returns sent / delivered / bounced / complained state plus open + click counters.
     * Get email status
     */
    async partnerEmailEmailsMessageIdGet(requestParameters: PartnerEmailEmailsMessageIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.partnerEmailEmailsMessageIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for partnerEmailSendBulkPost without sending the request
     */
    async partnerEmailSendBulkPostRequestOpts(requestParameters: PartnerEmailSendBulkPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling partnerEmailSendBulkPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/partner/email/send-bulk`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * One template + one verified From + N destinations, each with its own ReplacementData map. Equivalent to AWS SES SendBulkTemplatedEmail. Caps: 50 destinations × 50 recipients = 500 total per request.
     * Send bulk templated email
     */
    async partnerEmailSendBulkPostRaw(requestParameters: PartnerEmailSendBulkPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.partnerEmailSendBulkPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * One template + one verified From + N destinations, each with its own ReplacementData map. Equivalent to AWS SES SendBulkTemplatedEmail. Caps: 50 destinations × 50 recipients = 500 total per request.
     * Send bulk templated email
     */
    async partnerEmailSendBulkPost(requestParameters: PartnerEmailSendBulkPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.partnerEmailSendBulkPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for partnerEmailSendPost without sending the request
     */
    async partnerEmailSendPostRequestOpts(requestParameters: PartnerEmailSendPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling partnerEmailSendPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/partner/email/send`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Send a transactional or marketing email to up to 50 recipients (combined to + cc + bcc). Equivalent to AWS SES SendEmail.
     * Send email
     */
    async partnerEmailSendPostRaw(requestParameters: PartnerEmailSendPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.partnerEmailSendPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Send a transactional or marketing email to up to 50 recipients (combined to + cc + bcc). Equivalent to AWS SES SendEmail.
     * Send email
     */
    async partnerEmailSendPost(requestParameters: PartnerEmailSendPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.partnerEmailSendPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for partnerEmailSendRawPost without sending the request
     */
    async partnerEmailSendRawPostRequestOpts(requestParameters: PartnerEmailSendRawPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling partnerEmailSendRawPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/partner/email/send-raw`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Submit a pre-built RFC 5322 MIME message — useful when you\'ve already constructed the email body yourself (DKIM-ready, multipart, calendar invites, etc). Equivalent to AWS SES SendRawEmail. Max 10 MiB raw body.
     * Send raw MIME email
     */
    async partnerEmailSendRawPostRaw(requestParameters: PartnerEmailSendRawPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.partnerEmailSendRawPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Submit a pre-built RFC 5322 MIME message — useful when you\'ve already constructed the email body yourself (DKIM-ready, multipart, calendar invites, etc). Equivalent to AWS SES SendRawEmail. Max 10 MiB raw body.
     * Send raw MIME email
     */
    async partnerEmailSendRawPost(requestParameters: PartnerEmailSendRawPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.partnerEmailSendRawPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for partnerEmailSendTemplatePost without sending the request
     */
    async partnerEmailSendTemplatePostRequestOpts(requestParameters: PartnerEmailSendTemplatePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling partnerEmailSendTemplatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/partner/email/send-template`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Render a saved template with per-recipient variables and send it. Equivalent to AWS SES SendTemplatedEmail. Templates are pre-rendered at save time so per-send substitution is cheap.
     * Send templated email
     */
    async partnerEmailSendTemplatePostRaw(requestParameters: PartnerEmailSendTemplatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.partnerEmailSendTemplatePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Render a saved template with per-recipient variables and send it. Equivalent to AWS SES SendTemplatedEmail. Templates are pre-rendered at save time so per-send substitution is cheap.
     * Send templated email
     */
    async partnerEmailSendTemplatePost(requestParameters: PartnerEmailSendTemplatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.partnerEmailSendTemplatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
