/* tslint:disable */
/* eslint-disable */
/**
 * Splashify Pro API
 * REST endpoints for three product surfaces: 1. **Public API** under /public/_* — WhatsApp messaging, contacts, conversations, transactional email, Meta Conversions API. Authenticate with sk_live_… keys. 2. **Partner Email API** under /partner/email/_* — AWS-SES-shaped resold email platform: identities, configuration sets, templates, suppression, send, send-template, send-bulk, send-raw, quotas, stats, reputation, events. Authenticate with pk_live_… keys. 3. **App API** under /app/_* — the same surface the customer dashboard and the CLI/OpenClaw integrations use, authenticated with either an app session or an oc_live_… access token (`splashify auth login` / Settings → Developer → Access Tokens). Coverage here is partial — only endpoints touched by integrator reports are annotated so far, not the full surface. SDKs for Node.js, Python, and PHP are auto-generated from this spec.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@splashifypro.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
} from '../models/index';

export interface PartnerEmailConfigurationSetsGetRequest {
    customerId?: string;
}

export interface PartnerEmailConfigurationSetsIdDeleteRequest {
    id: string;
}

export interface PartnerEmailConfigurationSetsIdGetRequest {
    id: string;
}

export interface PartnerEmailConfigurationSetsIdPatchRequest {
    id: string;
    body: object;
}

export interface PartnerEmailConfigurationSetsPostRequest {
    body: object;
}

/**
 * PartnerEmailConfigurationSetsApi - interface
 * 
 * @export
 * @interface PartnerEmailConfigurationSetsApiInterface
 */
export interface PartnerEmailConfigurationSetsApiInterface {
    /**
     * Creates request options for partnerEmailConfigurationSetsGet without sending the request
     * @param {string} [customerId] Filter to one downstream customer
     * @throws {RequiredError}
     * @memberof PartnerEmailConfigurationSetsApiInterface
     */
    partnerEmailConfigurationSetsGetRequestOpts(requestParameters: PartnerEmailConfigurationSetsGetRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns every configuration set for the authenticated partner. A configuration set is a logical send context — partners typically create one per downstream end-customer or per app surface. Optional customer_id filter scopes the response to one downstream tenant.
     * @summary List configuration sets
     * @param {string} [customerId] Filter to one downstream customer
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnerEmailConfigurationSetsApiInterface
     */
    partnerEmailConfigurationSetsGetRaw(requestParameters: PartnerEmailConfigurationSetsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Returns every configuration set for the authenticated partner. A configuration set is a logical send context — partners typically create one per downstream end-customer or per app surface. Optional customer_id filter scopes the response to one downstream tenant.
     * List configuration sets
     */
    partnerEmailConfigurationSetsGet(requestParameters: PartnerEmailConfigurationSetsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for partnerEmailConfigurationSetsIdDelete without sending the request
     * @param {string} id Config set id
     * @throws {RequiredError}
     * @memberof PartnerEmailConfigurationSetsApiInterface
     */
    partnerEmailConfigurationSetsIdDeleteRequestOpts(requestParameters: PartnerEmailConfigurationSetsIdDeleteRequest): Promise<runtime.RequestOpts>;

    /**
     * Removes a configuration set + its event destinations. Sends already in flight against the deleted set complete normally; future sends referencing the deleted set fall back to \"no config set\" defaults (tracking on, no per-config-set webhooks).
     * @summary Delete configuration set
     * @param {string} id Config set id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnerEmailConfigurationSetsApiInterface
     */
    partnerEmailConfigurationSetsIdDeleteRaw(requestParameters: PartnerEmailConfigurationSetsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Removes a configuration set + its event destinations. Sends already in flight against the deleted set complete normally; future sends referencing the deleted set fall back to \"no config set\" defaults (tracking on, no per-config-set webhooks).
     * Delete configuration set
     */
    partnerEmailConfigurationSetsIdDelete(requestParameters: PartnerEmailConfigurationSetsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for partnerEmailConfigurationSetsIdGet without sending the request
     * @param {string} id Config set id
     * @throws {RequiredError}
     * @memberof PartnerEmailConfigurationSetsApiInterface
     */
    partnerEmailConfigurationSetsIdGetRequestOpts(requestParameters: PartnerEmailConfigurationSetsIdGetRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns one configuration set by id, including the current track_opens / track_clicks flags.
     * @summary Get configuration set
     * @param {string} id Config set id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnerEmailConfigurationSetsApiInterface
     */
    partnerEmailConfigurationSetsIdGetRaw(requestParameters: PartnerEmailConfigurationSetsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Returns one configuration set by id, including the current track_opens / track_clicks flags.
     * Get configuration set
     */
    partnerEmailConfigurationSetsIdGet(requestParameters: PartnerEmailConfigurationSetsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for partnerEmailConfigurationSetsIdPatch without sending the request
     * @param {string} id Config set id
     * @param {object} body Any subset of: name, description, suppression_options, reputation_tracking_enabled, sending_enabled, track_opens, track_clicks, custom_redirect_domain, tags.
     * @throws {RequiredError}
     * @memberof PartnerEmailConfigurationSetsApiInterface
     */
    partnerEmailConfigurationSetsIdPatchRequestOpts(requestParameters: PartnerEmailConfigurationSetsIdPatchRequest): Promise<runtime.RequestOpts>;

    /**
     * Patches an existing configuration set. All fields optional — only the keys you supply are updated. Use this to flip track_opens / track_clicks on existing config sets without recreating them.
     * @summary Update configuration set
     * @param {string} id Config set id
     * @param {object} body Any subset of: name, description, suppression_options, reputation_tracking_enabled, sending_enabled, track_opens, track_clicks, custom_redirect_domain, tags.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnerEmailConfigurationSetsApiInterface
     */
    partnerEmailConfigurationSetsIdPatchRaw(requestParameters: PartnerEmailConfigurationSetsIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Patches an existing configuration set. All fields optional — only the keys you supply are updated. Use this to flip track_opens / track_clicks on existing config sets without recreating them.
     * Update configuration set
     */
    partnerEmailConfigurationSetsIdPatch(requestParameters: PartnerEmailConfigurationSetsIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for partnerEmailConfigurationSetsPost without sending the request
     * @param {object} body Config set fields. Required: name. Optional: description, customer_id, suppression_options (NONE / BOUNCE / COMPLAINT / BOUNCE_AND_COMPLAINT), reputation_tracking_enabled (default true), sending_enabled (default true), track_opens (default true), track_clicks (default true), custom_redirect_domain, tags.
     * @throws {RequiredError}
     * @memberof PartnerEmailConfigurationSetsApiInterface
     */
    partnerEmailConfigurationSetsPostRequestOpts(requestParameters: PartnerEmailConfigurationSetsPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Creates a new configuration set. New flags track_opens + track_clicks (both default true) control whether Splashify Pro injects the open-tracking pixel + rewrites <a href> URLs through the click-tracking redirect on emails sent through this config set. Set both to false for transactional / privacy-sensitive flows. See partner-docs.splashifypro.com/webhooks/tracking for the full guide.
     * @summary Create configuration set
     * @param {object} body Config set fields. Required: name. Optional: description, customer_id, suppression_options (NONE / BOUNCE / COMPLAINT / BOUNCE_AND_COMPLAINT), reputation_tracking_enabled (default true), sending_enabled (default true), track_opens (default true), track_clicks (default true), custom_redirect_domain, tags.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnerEmailConfigurationSetsApiInterface
     */
    partnerEmailConfigurationSetsPostRaw(requestParameters: PartnerEmailConfigurationSetsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Creates a new configuration set. New flags track_opens + track_clicks (both default true) control whether Splashify Pro injects the open-tracking pixel + rewrites <a href> URLs through the click-tracking redirect on emails sent through this config set. Set both to false for transactional / privacy-sensitive flows. See partner-docs.splashifypro.com/webhooks/tracking for the full guide.
     * Create configuration set
     */
    partnerEmailConfigurationSetsPost(requestParameters: PartnerEmailConfigurationSetsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

}

/**
 * 
 */
export class PartnerEmailConfigurationSetsApi extends runtime.BaseAPI implements PartnerEmailConfigurationSetsApiInterface {

    /**
     * Creates request options for partnerEmailConfigurationSetsGet without sending the request
     */
    async partnerEmailConfigurationSetsGetRequestOpts(requestParameters: PartnerEmailConfigurationSetsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['customerId'] != null) {
            queryParameters['customer_id'] = requestParameters['customerId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/partner/email/configuration-sets`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns every configuration set for the authenticated partner. A configuration set is a logical send context — partners typically create one per downstream end-customer or per app surface. Optional customer_id filter scopes the response to one downstream tenant.
     * List configuration sets
     */
    async partnerEmailConfigurationSetsGetRaw(requestParameters: PartnerEmailConfigurationSetsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.partnerEmailConfigurationSetsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Returns every configuration set for the authenticated partner. A configuration set is a logical send context — partners typically create one per downstream end-customer or per app surface. Optional customer_id filter scopes the response to one downstream tenant.
     * List configuration sets
     */
    async partnerEmailConfigurationSetsGet(requestParameters: PartnerEmailConfigurationSetsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.partnerEmailConfigurationSetsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for partnerEmailConfigurationSetsIdDelete without sending the request
     */
    async partnerEmailConfigurationSetsIdDeleteRequestOpts(requestParameters: PartnerEmailConfigurationSetsIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling partnerEmailConfigurationSetsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/partner/email/configuration-sets/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Removes a configuration set + its event destinations. Sends already in flight against the deleted set complete normally; future sends referencing the deleted set fall back to \"no config set\" defaults (tracking on, no per-config-set webhooks).
     * Delete configuration set
     */
    async partnerEmailConfigurationSetsIdDeleteRaw(requestParameters: PartnerEmailConfigurationSetsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.partnerEmailConfigurationSetsIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Removes a configuration set + its event destinations. Sends already in flight against the deleted set complete normally; future sends referencing the deleted set fall back to \"no config set\" defaults (tracking on, no per-config-set webhooks).
     * Delete configuration set
     */
    async partnerEmailConfigurationSetsIdDelete(requestParameters: PartnerEmailConfigurationSetsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.partnerEmailConfigurationSetsIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for partnerEmailConfigurationSetsIdGet without sending the request
     */
    async partnerEmailConfigurationSetsIdGetRequestOpts(requestParameters: PartnerEmailConfigurationSetsIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling partnerEmailConfigurationSetsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/partner/email/configuration-sets/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns one configuration set by id, including the current track_opens / track_clicks flags.
     * Get configuration set
     */
    async partnerEmailConfigurationSetsIdGetRaw(requestParameters: PartnerEmailConfigurationSetsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.partnerEmailConfigurationSetsIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Returns one configuration set by id, including the current track_opens / track_clicks flags.
     * Get configuration set
     */
    async partnerEmailConfigurationSetsIdGet(requestParameters: PartnerEmailConfigurationSetsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.partnerEmailConfigurationSetsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for partnerEmailConfigurationSetsIdPatch without sending the request
     */
    async partnerEmailConfigurationSetsIdPatchRequestOpts(requestParameters: PartnerEmailConfigurationSetsIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling partnerEmailConfigurationSetsIdPatch().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling partnerEmailConfigurationSetsIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/partner/email/configuration-sets/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Patches an existing configuration set. All fields optional — only the keys you supply are updated. Use this to flip track_opens / track_clicks on existing config sets without recreating them.
     * Update configuration set
     */
    async partnerEmailConfigurationSetsIdPatchRaw(requestParameters: PartnerEmailConfigurationSetsIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.partnerEmailConfigurationSetsIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Patches an existing configuration set. All fields optional — only the keys you supply are updated. Use this to flip track_opens / track_clicks on existing config sets without recreating them.
     * Update configuration set
     */
    async partnerEmailConfigurationSetsIdPatch(requestParameters: PartnerEmailConfigurationSetsIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.partnerEmailConfigurationSetsIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for partnerEmailConfigurationSetsPost without sending the request
     */
    async partnerEmailConfigurationSetsPostRequestOpts(requestParameters: PartnerEmailConfigurationSetsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling partnerEmailConfigurationSetsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/partner/email/configuration-sets`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Creates a new configuration set. New flags track_opens + track_clicks (both default true) control whether Splashify Pro injects the open-tracking pixel + rewrites <a href> URLs through the click-tracking redirect on emails sent through this config set. Set both to false for transactional / privacy-sensitive flows. See partner-docs.splashifypro.com/webhooks/tracking for the full guide.
     * Create configuration set
     */
    async partnerEmailConfigurationSetsPostRaw(requestParameters: PartnerEmailConfigurationSetsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.partnerEmailConfigurationSetsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Creates a new configuration set. New flags track_opens + track_clicks (both default true) control whether Splashify Pro injects the open-tracking pixel + rewrites <a href> URLs through the click-tracking redirect on emails sent through this config set. Set both to false for transactional / privacy-sensitive flows. See partner-docs.splashifypro.com/webhooks/tracking for the full guide.
     * Create configuration set
     */
    async partnerEmailConfigurationSetsPost(requestParameters: PartnerEmailConfigurationSetsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.partnerEmailConfigurationSetsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
