/* tslint:disable */
/* eslint-disable */
/**
 * Splashify Pro API
 * REST endpoints for three product surfaces: 1. **Public API** under /public/_* — WhatsApp messaging, contacts, conversations, transactional email, Meta Conversions API. Authenticate with sk_live_… keys. 2. **Email API** under /partner/email/_*. Email sending for developers: identities, configuration sets, templates, suppression, send, send-template, send-bulk, send-raw, quotas, stats, reputation, events. Authenticate with pk_live_… keys. 3. **App API** under /app/_* — the same surface the customer dashboard and the CLI/OpenClaw integrations use, authenticated with either an app session or an oc_live_… access token (`splashify auth login` / Settings → Developer → Access Tokens). Coverage here is partial — only endpoints touched by integrator reports are annotated so far, not the full surface. SDKs for Node.js, Python, and PHP are auto-generated from this spec.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@splashifypro.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
} from '../models/index';

export interface PublicQrCodesIdDeleteRequest {
    id: string;
}

export interface PublicQrCodesIdPatchRequest {
    id: string;
    body: object;
}

export interface PublicQrCodesPostRequest {
    body: object;
}

/**
 * QRCodesApi - interface
 * 
 * @export
 * @interface QRCodesApiInterface
 */
export interface QRCodesApiInterface {
    /**
     * Creates request options for publicQrCodesGet without sending the request
     * @throws {RequiredError}
     * @memberof QRCodesApiInterface
     */
    publicQrCodesGetRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * Every WhatsApp QR code on the account with its link, scans and chats in the last 7 and 30 days, plus daily scans for 30 days.
     * @summary List QR codes
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QRCodesApiInterface
     */
    publicQrCodesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Every WhatsApp QR code on the account with its link, scans and chats in the last 7 and 30 days, plus daily scans for 30 days.
     * List QR codes
     */
    publicQrCodesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for publicQrCodesIdDelete without sending the request
     * @param {string} id QR code id
     * @throws {RequiredError}
     * @memberof QRCodesApiInterface
     */
    publicQrCodesIdDeleteRequestOpts(requestParameters: PublicQrCodesIdDeleteRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Delete a QR code
     * @param {string} id QR code id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QRCodesApiInterface
     */
    publicQrCodesIdDeleteRaw(requestParameters: PublicQrCodesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Delete a QR code
     */
    publicQrCodesIdDelete(requestParameters: PublicQrCodesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for publicQrCodesIdPatch without sending the request
     * @param {string} id QR code id
     * @param {object} body { name?, prefill? }
     * @throws {RequiredError}
     * @memberof QRCodesApiInterface
     */
    publicQrCodesIdPatchRequestOpts(requestParameters: PublicQrCodesIdPatchRequest): Promise<runtime.RequestOpts>;

    /**
     * Changes the name or the prefilled message. The link and the printed QR code stay the same.
     * @summary Update a QR code
     * @param {string} id QR code id
     * @param {object} body { name?, prefill? }
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QRCodesApiInterface
     */
    publicQrCodesIdPatchRaw(requestParameters: PublicQrCodesIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Changes the name or the prefilled message. The link and the printed QR code stay the same.
     * Update a QR code
     */
    publicQrCodesIdPatch(requestParameters: PublicQrCodesIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for publicQrCodesPost without sending the request
     * @param {object} body { name, prefill? }
     * @throws {RequiredError}
     * @memberof QRCodesApiInterface
     */
    publicQrCodesPostRequestOpts(requestParameters: PublicQrCodesPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Creates a tracked WhatsApp link and QR code. prefill is the message the customer\'s chat opens with (up to 500 characters). Up to 200 QR codes per account.
     * @summary Create a QR code
     * @param {object} body { name, prefill? }
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QRCodesApiInterface
     */
    publicQrCodesPostRaw(requestParameters: PublicQrCodesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Creates a tracked WhatsApp link and QR code. prefill is the message the customer\'s chat opens with (up to 500 characters). Up to 200 QR codes per account.
     * Create a QR code
     */
    publicQrCodesPost(requestParameters: PublicQrCodesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

}

/**
 * 
 */
export class QRCodesApi extends runtime.BaseAPI implements QRCodesApiInterface {

    /**
     * Creates request options for publicQrCodesGet without sending the request
     */
    async publicQrCodesGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/qr-codes`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Every WhatsApp QR code on the account with its link, scans and chats in the last 7 and 30 days, plus daily scans for 30 days.
     * List QR codes
     */
    async publicQrCodesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.publicQrCodesGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Every WhatsApp QR code on the account with its link, scans and chats in the last 7 and 30 days, plus daily scans for 30 days.
     * List QR codes
     */
    async publicQrCodesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicQrCodesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicQrCodesIdDelete without sending the request
     */
    async publicQrCodesIdDeleteRequestOpts(requestParameters: PublicQrCodesIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling publicQrCodesIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/qr-codes/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a QR code
     */
    async publicQrCodesIdDeleteRaw(requestParameters: PublicQrCodesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.publicQrCodesIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Delete a QR code
     */
    async publicQrCodesIdDelete(requestParameters: PublicQrCodesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicQrCodesIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicQrCodesIdPatch without sending the request
     */
    async publicQrCodesIdPatchRequestOpts(requestParameters: PublicQrCodesIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling publicQrCodesIdPatch().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling publicQrCodesIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/qr-codes/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Changes the name or the prefilled message. The link and the printed QR code stay the same.
     * Update a QR code
     */
    async publicQrCodesIdPatchRaw(requestParameters: PublicQrCodesIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.publicQrCodesIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Changes the name or the prefilled message. The link and the printed QR code stay the same.
     * Update a QR code
     */
    async publicQrCodesIdPatch(requestParameters: PublicQrCodesIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicQrCodesIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicQrCodesPost without sending the request
     */
    async publicQrCodesPostRequestOpts(requestParameters: PublicQrCodesPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling publicQrCodesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/qr-codes`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Creates a tracked WhatsApp link and QR code. prefill is the message the customer\'s chat opens with (up to 500 characters). Up to 200 QR codes per account.
     * Create a QR code
     */
    async publicQrCodesPostRaw(requestParameters: PublicQrCodesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.publicQrCodesPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Creates a tracked WhatsApp link and QR code. prefill is the message the customer\'s chat opens with (up to 500 characters). Up to 200 QR codes per account.
     * Create a QR code
     */
    async publicQrCodesPost(requestParameters: PublicQrCodesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicQrCodesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
