/* tslint:disable */
/* eslint-disable */
/**
 * Splashify Pro API
 * REST endpoints for two product surfaces: 1. **Public API** under /public/_* — WhatsApp messaging, contacts, conversations, transactional email, Meta Conversions API. Authenticate with sk_live_… keys. 2. **Partner Email API** under /partner/email/_* — AWS-SES-shaped resold email platform: identities, configuration sets, templates, suppression, send, send-template, send-bulk, send-raw, quotas, stats, reputation, events. Authenticate with pk_live_… keys. SDKs for Node.js, Python, and PHP are auto-generated from this spec.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@splashifypro.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    HandlersCheckCapabilityRequest,
} from '../models/index';

export interface PublicRcsCheckCapabilityPostRequest {
    body: HandlersCheckCapabilityRequest;
}

export interface PublicRcsSendPostRequest {
    body: object;
}

export interface PublicRcsSendTemplatePostRequest {
    body: object;
}

/**
 * RCSApi - interface
 * 
 * @export
 * @interface RCSApiInterface
 */
export interface RCSApiInterface {
    /**
     * Creates request options for publicRcsCheckCapabilityPost without sending the request
     * @param {HandlersCheckCapabilityRequest} body phone (single, E.164) OR phones (array of E.164)
     * @throws {RequiredError}
     * @memberof RCSApiInterface
     */
    publicRcsCheckCapabilityPostRequestOpts(requestParameters: PublicRcsCheckCapabilityPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns the subset of the given phone numbers that are RCS-reachable on JioCX. Accepts a single phone or a bulk list (up to 10,000). Fail-open — if the gateway is momentarily unavailable, the input is returned unchanged so send flows are not blocked.
     * @summary Check RCS reachability
     * @param {HandlersCheckCapabilityRequest} body phone (single, E.164) OR phones (array of E.164)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RCSApiInterface
     */
    publicRcsCheckCapabilityPostRaw(requestParameters: PublicRcsCheckCapabilityPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Returns the subset of the given phone numbers that are RCS-reachable on JioCX. Accepts a single phone or a bulk list (up to 10,000). Fail-open — if the gateway is momentarily unavailable, the input is returned unchanged so send flows are not blocked.
     * Check RCS reachability
     */
    publicRcsCheckCapabilityPost(requestParameters: PublicRcsCheckCapabilityPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for publicRcsSendPost without sending the request
     * @param {object} body Free-form: { to, type, ... }. Template: { to, template_id, variables? }
     * @throws {RequiredError}
     * @memberof RCSApiInterface
     */
    publicRcsSendPostRequestOpts(requestParameters: PublicRcsSendPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Send any RCS message type — text, media, card, multiple_cards — OR reference a stored approved template by template_id with positional variables. Presence of template_id picks the template path.
     * @summary Send an RCS message (free-form or from a stored template)
     * @param {object} body Free-form: { to, type, ... }. Template: { to, template_id, variables? }
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RCSApiInterface
     */
    publicRcsSendPostRaw(requestParameters: PublicRcsSendPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Send any RCS message type — text, media, card, multiple_cards — OR reference a stored approved template by template_id with positional variables. Presence of template_id picks the template path.
     * Send an RCS message (free-form or from a stored template)
     */
    publicRcsSendPost(requestParameters: PublicRcsSendPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for publicRcsSendTemplatePost without sending the request
     * @param {object} body RCS template payload (to, template_id, variables)
     * @throws {RequiredError}
     * @memberof RCSApiInterface
     */
    publicRcsSendTemplatePostRequestOpts(requestParameters: PublicRcsSendTemplatePostRequest): Promise<runtime.RequestOpts>;

    /**
     * Send a stored, approved RCS template. Positional {#varN#} placeholders are filled from the variables array, in order. Deprecated alias. POST /rcs/send accepts { to, template_id, variables } directly. Kept for backward-compatibility.
     * @summary (Deprecated) Send an approved RCS template — use POST /rcs/send instead
     * @param {object} body RCS template payload (to, template_id, variables)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RCSApiInterface
     */
    publicRcsSendTemplatePostRaw(requestParameters: PublicRcsSendTemplatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Send a stored, approved RCS template. Positional {#varN#} placeholders are filled from the variables array, in order. Deprecated alias. POST /rcs/send accepts { to, template_id, variables } directly. Kept for backward-compatibility.
     * (Deprecated) Send an approved RCS template — use POST /rcs/send instead
     */
    publicRcsSendTemplatePost(requestParameters: PublicRcsSendTemplatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

}

/**
 * 
 */
export class RCSApi extends runtime.BaseAPI implements RCSApiInterface {

    /**
     * Creates request options for publicRcsCheckCapabilityPost without sending the request
     */
    async publicRcsCheckCapabilityPostRequestOpts(requestParameters: PublicRcsCheckCapabilityPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling publicRcsCheckCapabilityPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/rcs/check-capability`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'],
        };
    }

    /**
     * Returns the subset of the given phone numbers that are RCS-reachable on JioCX. Accepts a single phone or a bulk list (up to 10,000). Fail-open — if the gateway is momentarily unavailable, the input is returned unchanged so send flows are not blocked.
     * Check RCS reachability
     */
    async publicRcsCheckCapabilityPostRaw(requestParameters: PublicRcsCheckCapabilityPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.publicRcsCheckCapabilityPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Returns the subset of the given phone numbers that are RCS-reachable on JioCX. Accepts a single phone or a bulk list (up to 10,000). Fail-open — if the gateway is momentarily unavailable, the input is returned unchanged so send flows are not blocked.
     * Check RCS reachability
     */
    async publicRcsCheckCapabilityPost(requestParameters: PublicRcsCheckCapabilityPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicRcsCheckCapabilityPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicRcsSendPost without sending the request
     */
    async publicRcsSendPostRequestOpts(requestParameters: PublicRcsSendPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling publicRcsSendPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/rcs/send`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Send any RCS message type — text, media, card, multiple_cards — OR reference a stored approved template by template_id with positional variables. Presence of template_id picks the template path.
     * Send an RCS message (free-form or from a stored template)
     */
    async publicRcsSendPostRaw(requestParameters: PublicRcsSendPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.publicRcsSendPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Send any RCS message type — text, media, card, multiple_cards — OR reference a stored approved template by template_id with positional variables. Presence of template_id picks the template path.
     * Send an RCS message (free-form or from a stored template)
     */
    async publicRcsSendPost(requestParameters: PublicRcsSendPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicRcsSendPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicRcsSendTemplatePost without sending the request
     */
    async publicRcsSendTemplatePostRequestOpts(requestParameters: PublicRcsSendTemplatePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling publicRcsSendTemplatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/rcs/send-template`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Send a stored, approved RCS template. Positional {#varN#} placeholders are filled from the variables array, in order. Deprecated alias. POST /rcs/send accepts { to, template_id, variables } directly. Kept for backward-compatibility.
     * (Deprecated) Send an approved RCS template — use POST /rcs/send instead
     */
    async publicRcsSendTemplatePostRaw(requestParameters: PublicRcsSendTemplatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.publicRcsSendTemplatePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Send a stored, approved RCS template. Positional {#varN#} placeholders are filled from the variables array, in order. Deprecated alias. POST /rcs/send accepts { to, template_id, variables } directly. Kept for backward-compatibility.
     * (Deprecated) Send an approved RCS template — use POST /rcs/send instead
     */
    async publicRcsSendTemplatePost(requestParameters: PublicRcsSendTemplatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicRcsSendTemplatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
