/* tslint:disable */
/* eslint-disable */
/**
 * Splashify Pro API
 * REST endpoints for three product surfaces: 1. **Public API** under /public/_* — WhatsApp messaging, contacts, conversations, transactional email, Meta Conversions API. Authenticate with sk_live_… keys. 2. **Email API** under /partner/email/_*. Email sending for developers: identities, configuration sets, templates, suppression, send, send-template, send-bulk, send-raw, quotas, stats, reputation, events. Authenticate with pk_live_… keys. 3. **App API** under /app/_* — the same surface the customer dashboard and the CLI/OpenClaw integrations use, authenticated with either an app session or an oc_live_… access token (`splashify auth login` / Settings → Developer → Access Tokens). Coverage here is partial — only endpoints touched by integrator reports are annotated so far, not the full surface. SDKs for Node.js, Python, and PHP are auto-generated from this spec.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@splashifypro.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
} from '../models/index';

export interface PublicSmsBulkBulkIdGetRequest {
    bulkId: string;
}

export interface PublicSmsMessagesMessageIdGetRequest {
    messageId: string;
}

export interface PublicSmsSendBulkPostRequest {
    body: object;
    idempotencyKey?: string;
}

export interface PublicSmsSendPostRequest {
    body: object;
    idempotencyKey?: string;
}

/**
 * SMSApi - interface
 * 
 * @export
 * @interface SMSApiInterface
 */
export interface SMSApiInterface {
    /**
     * Creates request options for publicSmsBulkBulkIdGet without sending the request
     * @param {string} bulkId bulk_id from /public/sms/send-bulk
     * @throws {RequiredError}
     * @memberof SMSApiInterface
     */
    publicSmsBulkBulkIdGetRequestOpts(requestParameters: PublicSmsBulkBulkIdGetRequest): Promise<runtime.RequestOpts>;

    /**
     * Progress of a bulk send by the bulk_id /public/sms/send-bulk returned. status is queued, running, completed, stopped or cancelled. failed counts numbers the network refused plus delivery failures reported so far.
     * @summary Bulk send progress
     * @param {string} bulkId bulk_id from /public/sms/send-bulk
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SMSApiInterface
     */
    publicSmsBulkBulkIdGetRaw(requestParameters: PublicSmsBulkBulkIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Progress of a bulk send by the bulk_id /public/sms/send-bulk returned. status is queued, running, completed, stopped or cancelled. failed counts numbers the network refused plus delivery failures reported so far.
     * Bulk send progress
     */
    publicSmsBulkBulkIdGet(requestParameters: PublicSmsBulkBulkIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for publicSmsMessagesMessageIdGet without sending the request
     * @param {string} messageId message_id from /public/sms/send
     * @throws {RequiredError}
     * @memberof SMSApiInterface
     */
    publicSmsMessagesMessageIdGetRequestOpts(requestParameters: PublicSmsMessagesMessageIdGetRequest): Promise<runtime.RequestOpts>;

    /**
     * Status of one message by the message_id /public/sms/send returned. status is queued, sent, delivered, failed or rejected. error says why when it did not arrive.
     * @summary One SMS status
     * @param {string} messageId message_id from /public/sms/send
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SMSApiInterface
     */
    publicSmsMessagesMessageIdGetRaw(requestParameters: PublicSmsMessagesMessageIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Status of one message by the message_id /public/sms/send returned. status is queued, sent, delivered, failed or rejected. error says why when it did not arrive.
     * One SMS status
     */
    publicSmsMessagesMessageIdGet(requestParameters: PublicSmsMessagesMessageIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for publicSmsSendBulkPost without sending the request
     * @param {object} body { dlt_template_id, name?, messages: [{ to, variables[] }] }
     * @param {string} [idempotencyKey] Makes a retry safe: a repeat within 24 hours gets the same bulk_id back with its current status and replayed true, and nothing is queued again
     * @throws {RequiredError}
     * @memberof SMSApiInterface
     */
    publicSmsSendBulkPostRequestOpts(requestParameters: PublicSmsSendBulkPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Queues 1 to 1,000 messages on one approved template of any DLT type. Every row is checked first. A wrong variable count is a 400 naming the row. Invalid numbers, repeats and opted-out contacts are skipped and counted. Refused with 402 and nothing queued when the wallet cannot cover the estimate.
     * @summary Send one template to many numbers
     * @param {object} body { dlt_template_id, name?, messages: [{ to, variables[] }] }
     * @param {string} [idempotencyKey] Makes a retry safe: a repeat within 24 hours gets the same bulk_id back with its current status and replayed true, and nothing is queued again
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SMSApiInterface
     */
    publicSmsSendBulkPostRaw(requestParameters: PublicSmsSendBulkPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Queues 1 to 1,000 messages on one approved template of any DLT type. Every row is checked first. A wrong variable count is a 400 naming the row. Invalid numbers, repeats and opted-out contacts are skipped and counted. Refused with 402 and nothing queued when the wallet cannot cover the estimate.
     * Send one template to many numbers
     */
    publicSmsSendBulkPost(requestParameters: PublicSmsSendBulkPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for publicSmsSendPost without sending the request
     * @param {object} body { to, dlt_template_id, variables[] }
     * @param {string} [idempotencyKey] Makes a retry safe: a repeat within 24 hours gets the first answer back with replayed true, and nothing is sent again
     * @throws {RequiredError}
     * @memberof SMSApiInterface
     */
    publicSmsSendPostRequestOpts(requestParameters: PublicSmsSendPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Sends one DLT SMS from an approved template to an Indian mobile number. The template decides the DLT type, the sender ID and the price. variables fill the template\'s {#var#} slots in order, 30 characters at most each. A message the network refuses is a 200 with accepted false.
     * @summary Send one SMS
     * @param {object} body { to, dlt_template_id, variables[] }
     * @param {string} [idempotencyKey] Makes a retry safe: a repeat within 24 hours gets the first answer back with replayed true, and nothing is sent again
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SMSApiInterface
     */
    publicSmsSendPostRaw(requestParameters: PublicSmsSendPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Sends one DLT SMS from an approved template to an Indian mobile number. The template decides the DLT type, the sender ID and the price. variables fill the template\'s {#var#} slots in order, 30 characters at most each. A message the network refuses is a 200 with accepted false.
     * Send one SMS
     */
    publicSmsSendPost(requestParameters: PublicSmsSendPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for publicSmsSendersGet without sending the request
     * @throws {RequiredError}
     * @memberof SMSApiInterface
     */
    publicSmsSendersGetRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * The sender IDs on the account. status is approved, pending or rejected; type is the DLT type the sender ID was registered for.
     * @summary SMS sender IDs
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SMSApiInterface
     */
    publicSmsSendersGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * The sender IDs on the account. status is approved, pending or rejected; type is the DLT type the sender ID was registered for.
     * SMS sender IDs
     */
    publicSmsSendersGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for publicSmsTemplatesGet without sending the request
     * @throws {RequiredError}
     * @memberof SMSApiInterface
     */
    publicSmsTemplatesGetRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * The approved DLT templates on the account. type is promotional, transactional, service_implicit or service_explicit; variables is how many {#var#} slots the body has.
     * @summary Approved SMS templates
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SMSApiInterface
     */
    publicSmsTemplatesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * The approved DLT templates on the account. type is promotional, transactional, service_implicit or service_explicit; variables is how many {#var#} slots the body has.
     * Approved SMS templates
     */
    publicSmsTemplatesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

}

/**
 * 
 */
export class SMSApi extends runtime.BaseAPI implements SMSApiInterface {

    /**
     * Creates request options for publicSmsBulkBulkIdGet without sending the request
     */
    async publicSmsBulkBulkIdGetRequestOpts(requestParameters: PublicSmsBulkBulkIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bulkId'] == null) {
            throw new runtime.RequiredError(
                'bulkId',
                'Required parameter "bulkId" was null or undefined when calling publicSmsBulkBulkIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/sms/bulk/{bulk_id}`;
        urlPath = urlPath.replace('{bulk_id}', encodeURIComponent(String(requestParameters['bulkId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Progress of a bulk send by the bulk_id /public/sms/send-bulk returned. status is queued, running, completed, stopped or cancelled. failed counts numbers the network refused plus delivery failures reported so far.
     * Bulk send progress
     */
    async publicSmsBulkBulkIdGetRaw(requestParameters: PublicSmsBulkBulkIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.publicSmsBulkBulkIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Progress of a bulk send by the bulk_id /public/sms/send-bulk returned. status is queued, running, completed, stopped or cancelled. failed counts numbers the network refused plus delivery failures reported so far.
     * Bulk send progress
     */
    async publicSmsBulkBulkIdGet(requestParameters: PublicSmsBulkBulkIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicSmsBulkBulkIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicSmsMessagesMessageIdGet without sending the request
     */
    async publicSmsMessagesMessageIdGetRequestOpts(requestParameters: PublicSmsMessagesMessageIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['messageId'] == null) {
            throw new runtime.RequiredError(
                'messageId',
                'Required parameter "messageId" was null or undefined when calling publicSmsMessagesMessageIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/sms/messages/{message_id}`;
        urlPath = urlPath.replace('{message_id}', encodeURIComponent(String(requestParameters['messageId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Status of one message by the message_id /public/sms/send returned. status is queued, sent, delivered, failed or rejected. error says why when it did not arrive.
     * One SMS status
     */
    async publicSmsMessagesMessageIdGetRaw(requestParameters: PublicSmsMessagesMessageIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.publicSmsMessagesMessageIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Status of one message by the message_id /public/sms/send returned. status is queued, sent, delivered, failed or rejected. error says why when it did not arrive.
     * One SMS status
     */
    async publicSmsMessagesMessageIdGet(requestParameters: PublicSmsMessagesMessageIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicSmsMessagesMessageIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicSmsSendBulkPost without sending the request
     */
    async publicSmsSendBulkPostRequestOpts(requestParameters: PublicSmsSendBulkPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling publicSmsSendBulkPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/sms/send-bulk`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Queues 1 to 1,000 messages on one approved template of any DLT type. Every row is checked first. A wrong variable count is a 400 naming the row. Invalid numbers, repeats and opted-out contacts are skipped and counted. Refused with 402 and nothing queued when the wallet cannot cover the estimate.
     * Send one template to many numbers
     */
    async publicSmsSendBulkPostRaw(requestParameters: PublicSmsSendBulkPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.publicSmsSendBulkPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Queues 1 to 1,000 messages on one approved template of any DLT type. Every row is checked first. A wrong variable count is a 400 naming the row. Invalid numbers, repeats and opted-out contacts are skipped and counted. Refused with 402 and nothing queued when the wallet cannot cover the estimate.
     * Send one template to many numbers
     */
    async publicSmsSendBulkPost(requestParameters: PublicSmsSendBulkPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicSmsSendBulkPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicSmsSendPost without sending the request
     */
    async publicSmsSendPostRequestOpts(requestParameters: PublicSmsSendPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling publicSmsSendPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/sms/send`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Sends one DLT SMS from an approved template to an Indian mobile number. The template decides the DLT type, the sender ID and the price. variables fill the template\'s {#var#} slots in order, 30 characters at most each. A message the network refuses is a 200 with accepted false.
     * Send one SMS
     */
    async publicSmsSendPostRaw(requestParameters: PublicSmsSendPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.publicSmsSendPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Sends one DLT SMS from an approved template to an Indian mobile number. The template decides the DLT type, the sender ID and the price. variables fill the template\'s {#var#} slots in order, 30 characters at most each. A message the network refuses is a 200 with accepted false.
     * Send one SMS
     */
    async publicSmsSendPost(requestParameters: PublicSmsSendPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicSmsSendPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicSmsSendersGet without sending the request
     */
    async publicSmsSendersGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/sms/senders`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * The sender IDs on the account. status is approved, pending or rejected; type is the DLT type the sender ID was registered for.
     * SMS sender IDs
     */
    async publicSmsSendersGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.publicSmsSendersGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * The sender IDs on the account. status is approved, pending or rejected; type is the DLT type the sender ID was registered for.
     * SMS sender IDs
     */
    async publicSmsSendersGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicSmsSendersGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicSmsTemplatesGet without sending the request
     */
    async publicSmsTemplatesGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/sms/templates`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * The approved DLT templates on the account. type is promotional, transactional, service_implicit or service_explicit; variables is how many {#var#} slots the body has.
     * Approved SMS templates
     */
    async publicSmsTemplatesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.publicSmsTemplatesGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * The approved DLT templates on the account. type is promotional, transactional, service_implicit or service_explicit; variables is how many {#var#} slots the body has.
     * Approved SMS templates
     */
    async publicSmsTemplatesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicSmsTemplatesGetRaw(initOverrides);
        return await response.value();
    }

}
