/* tslint:disable */
/* eslint-disable */
/**
 * Splashify Pro API
 * REST endpoints for three product surfaces: 1. **Public API** under /public/_* — WhatsApp messaging, contacts, conversations, transactional email, Meta Conversions API. Authenticate with sk_live_… keys. 2. **Email API** under /partner/email/_*. Email sending for developers: identities, configuration sets, templates, suppression, send, send-template, send-bulk, send-raw, quotas, stats, reputation, events. Authenticate with pk_live_… keys. 3. **App API** under /app/_* — the same surface the customer dashboard and the CLI/OpenClaw integrations use, authenticated with either an app session or an oc_live_… access token (`splashify auth login` / Settings → Developer → Access Tokens). Coverage here is partial — only endpoints touched by integrator reports are annotated so far, not the full surface. SDKs for Node.js, Python, and PHP are auto-generated from this spec.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@splashifypro.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
} from '../models/index';

export interface PublicTemplatesGetRequest {
    status?: string;
}

export interface PublicTemplatesInsightsGetRequest {
    days?: number;
}

/**
 * TemplatesApi - interface
 * 
 * @export
 * @interface TemplatesApiInterface
 */
export interface TemplatesApiInterface {
    /**
     * Creates request options for publicTemplatesGet without sending the request
     * @param {string} [status] Only this status, for example APPROVED
     * @throws {RequiredError}
     * @memberof TemplatesApiInterface
     */
    publicTemplatesGetRequestOpts(requestParameters: PublicTemplatesGetRequest): Promise<runtime.RequestOpts>;

    /**
     * List the WhatsApp message templates of your account, with their approval status.
     * @summary List templates
     * @param {string} [status] Only this status, for example APPROVED
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemplatesApiInterface
     */
    publicTemplatesGetRaw(requestParameters: PublicTemplatesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * List the WhatsApp message templates of your account, with their approval status.
     * List templates
     */
    publicTemplatesGet(requestParameters: PublicTemplatesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for publicTemplatesInsightsGet without sending the request
     * @param {number} [days] 30 (default) or 90
     * @throws {RequiredError}
     * @memberof TemplatesApiInterface
     */
    publicTemplatesInsightsGetRequestOpts(requestParameters: PublicTemplatesInsightsGetRequest): Promise<runtime.RequestOpts>;

    /**
     * Sent, delivered, read, button click and reply rates per template over the last 30 or 90 days, with the account average.
     * @summary Template insights
     * @param {number} [days] 30 (default) or 90
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemplatesApiInterface
     */
    publicTemplatesInsightsGetRaw(requestParameters: PublicTemplatesInsightsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Sent, delivered, read, button click and reply rates per template over the last 30 or 90 days, with the account average.
     * Template insights
     */
    publicTemplatesInsightsGet(requestParameters: PublicTemplatesInsightsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

}

/**
 * 
 */
export class TemplatesApi extends runtime.BaseAPI implements TemplatesApiInterface {

    /**
     * Creates request options for publicTemplatesGet without sending the request
     */
    async publicTemplatesGetRequestOpts(requestParameters: PublicTemplatesGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/templates`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List the WhatsApp message templates of your account, with their approval status.
     * List templates
     */
    async publicTemplatesGetRaw(requestParameters: PublicTemplatesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.publicTemplatesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * List the WhatsApp message templates of your account, with their approval status.
     * List templates
     */
    async publicTemplatesGet(requestParameters: PublicTemplatesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicTemplatesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicTemplatesInsightsGet without sending the request
     */
    async publicTemplatesInsightsGetRequestOpts(requestParameters: PublicTemplatesInsightsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['days'] != null) {
            queryParameters['days'] = requestParameters['days'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/templates/insights`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Sent, delivered, read, button click and reply rates per template over the last 30 or 90 days, with the account average.
     * Template insights
     */
    async publicTemplatesInsightsGetRaw(requestParameters: PublicTemplatesInsightsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.publicTemplatesInsightsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Sent, delivered, read, button click and reply rates per template over the last 30 or 90 days, with the account average.
     * Template insights
     */
    async publicTemplatesInsightsGet(requestParameters: PublicTemplatesInsightsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicTemplatesInsightsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
