/* tslint:disable */
/* eslint-disable */
/**
 * Splashify Pro API
 * REST endpoints for three product surfaces: 1. **Public API** under /public/_* — WhatsApp messaging, contacts, conversations, transactional email, Meta Conversions API. Authenticate with sk_live_… keys. 2. **Partner Email API** under /partner/email/_* — AWS-SES-shaped resold email platform: identities, configuration sets, templates, suppression, send, send-template, send-bulk, send-raw, quotas, stats, reputation, events. Authenticate with pk_live_… keys. 3. **App API** under /app/_* — the same surface the customer dashboard and the CLI/OpenClaw integrations use, authenticated with either an app session or an oc_live_… access token (`splashify auth login` / Settings → Developer → Access Tokens). Coverage here is partial — only endpoints touched by integrator reports are annotated so far, not the full surface. SDKs for Node.js, Python, and PHP are auto-generated from this spec.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@splashifypro.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
} from '../models/index';

export interface AppWalletAlertsPutRequest {
    body: object;
}

/**
 * WalletApi - interface
 * 
 * @export
 * @interface WalletApiInterface
 */
export interface WalletApiInterface {
    /**
     * Creates request options for appWalletAlertsGet without sending the request
     * @throws {RequiredError}
     * @memberof WalletApiInterface
     */
    appWalletAlertsGetRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * The balance at which the wallet_low webhook fires. is_default is true when the account has not configured one and the ₹100 platform default is in effect.
     * @summary Get the low-balance alert threshold
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WalletApiInterface
     */
    appWalletAlertsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * The balance at which the wallet_low webhook fires. is_default is true when the account has not configured one and the ₹100 platform default is in effect.
     * Get the low-balance alert threshold
     */
    appWalletAlertsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for appWalletAlertsPut without sending the request
     * @param {object} body { low_balance_threshold: number }
     * @throws {RequiredError}
     * @memberof WalletApiInterface
     */
    appWalletAlertsPutRequestOpts(requestParameters: AppWalletAlertsPutRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Set the low-balance alert threshold
     * @param {object} body { low_balance_threshold: number }
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WalletApiInterface
     */
    appWalletAlertsPutRaw(requestParameters: AppWalletAlertsPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Set the low-balance alert threshold
     */
    appWalletAlertsPut(requestParameters: AppWalletAlertsPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for appWalletInfoGet without sending the request
     * @throws {RequiredError}
     * @memberof WalletApiInterface
     */
    appWalletInfoGetRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * Wallet balance and last recharge info for the current app user. spent_balance accumulates from every wallet debit (direct sends and broadcasts) — accounts predating this accumulation may see a jump rather than a full history.
     * @summary Wallet balance
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WalletApiInterface
     */
    appWalletInfoGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Wallet balance and last recharge info for the current app user. spent_balance accumulates from every wallet debit (direct sends and broadcasts) — accounts predating this accumulation may see a jump rather than a full history.
     * Wallet balance
     */
    appWalletInfoGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

}

/**
 * 
 */
export class WalletApi extends runtime.BaseAPI implements WalletApiInterface {

    /**
     * Creates request options for appWalletAlertsGet without sending the request
     */
    async appWalletAlertsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/app/wallet/alerts`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * The balance at which the wallet_low webhook fires. is_default is true when the account has not configured one and the ₹100 platform default is in effect.
     * Get the low-balance alert threshold
     */
    async appWalletAlertsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.appWalletAlertsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * The balance at which the wallet_low webhook fires. is_default is true when the account has not configured one and the ₹100 platform default is in effect.
     * Get the low-balance alert threshold
     */
    async appWalletAlertsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.appWalletAlertsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for appWalletAlertsPut without sending the request
     */
    async appWalletAlertsPutRequestOpts(requestParameters: AppWalletAlertsPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling appWalletAlertsPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/app/wallet/alerts`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Set the low-balance alert threshold
     */
    async appWalletAlertsPutRaw(requestParameters: AppWalletAlertsPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.appWalletAlertsPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Set the low-balance alert threshold
     */
    async appWalletAlertsPut(requestParameters: AppWalletAlertsPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.appWalletAlertsPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for appWalletInfoGet without sending the request
     */
    async appWalletInfoGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/app/wallet/info`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Wallet balance and last recharge info for the current app user. spent_balance accumulates from every wallet debit (direct sends and broadcasts) — accounts predating this accumulation may see a jump rather than a full history.
     * Wallet balance
     */
    async appWalletInfoGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.appWalletInfoGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Wallet balance and last recharge info for the current app user. spent_balance accumulates from every wallet debit (direct sends and broadcasts) — accounts predating this accumulation may see a jump rather than a full history.
     * Wallet balance
     */
    async appWalletInfoGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.appWalletInfoGetRaw(initOverrides);
        return await response.value();
    }

}
