/* tslint:disable */
/* eslint-disable */
/**
 * Splashify Pro API
 * REST endpoints for three product surfaces: 1. **Public API** under /public/_* — WhatsApp messaging, contacts, conversations, transactional email, Meta Conversions API. Authenticate with sk_live_… keys. 2. **Partner Email API** under /partner/email/_* — AWS-SES-shaped resold email platform: identities, configuration sets, templates, suppression, send, send-template, send-bulk, send-raw, quotas, stats, reputation, events. Authenticate with pk_live_… keys. 3. **App API** under /app/_* — the same surface the customer dashboard and the CLI/OpenClaw integrations use, authenticated with either an app session or an oc_live_… access token (`splashify auth login` / Settings → Developer → Access Tokens). Coverage here is partial — only endpoints touched by integrator reports are annotated so far, not the full surface. SDKs for Node.js, Python, and PHP are auto-generated from this spec.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@splashifypro.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
} from '../models/index';

export interface AppWebhooksIdDeleteRequest {
    id: string;
}

export interface AppWebhooksIdGetRequest {
    id: string;
}

export interface AppWebhooksIdPatchRequest {
    id: string;
    body?: object;
}

export interface AppWebhooksIdRotateSecretPostRequest {
    id: string;
}

export interface AppWebhooksIdTestPostRequest {
    id: string;
}

export interface AppWebhooksPostRequest {
    body: object;
}

/**
 * WebhooksApi - interface
 * 
 * @export
 * @interface WebhooksApiInterface
 */
export interface WebhooksApiInterface {
    /**
     * Creates request options for appWebhooksEventsGet without sending the request
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    appWebhooksEventsGetRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List subscribable webhook event names
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    appWebhooksEventsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * List subscribable webhook event names
     */
    appWebhooksEventsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for appWebhooksGet without sending the request
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    appWebhooksGetRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List registered webhooks
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    appWebhooksGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * List registered webhooks
     */
    appWebhooksGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for appWebhooksIdDelete without sending the request
     * @param {string} id Webhook ID
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    appWebhooksIdDeleteRequestOpts(requestParameters: AppWebhooksIdDeleteRequest): Promise<runtime.RequestOpts>;

    /**
     * Deleting the webhook backing Settings → Developer → Configure Webhook resets that page to \"not configured\" rather than leaving it pointing at a dangling id.
     * @summary Delete a webhook
     * @param {string} id Webhook ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    appWebhooksIdDeleteRaw(requestParameters: AppWebhooksIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Deleting the webhook backing Settings → Developer → Configure Webhook resets that page to \"not configured\" rather than leaving it pointing at a dangling id.
     * Delete a webhook
     */
    appWebhooksIdDelete(requestParameters: AppWebhooksIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for appWebhooksIdGet without sending the request
     * @param {string} id Webhook ID
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    appWebhooksIdGetRequestOpts(requestParameters: AppWebhooksIdGetRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns one webhook regardless of whether it was created via this API or Settings → Developer → Configure Webhook — same fields either way. The secret is never echoed here; read it from GET /app/developer/settings (console webhook) or the create/rotate-secret response (only shown once).
     * @summary Get a webhook
     * @param {string} id Webhook ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    appWebhooksIdGetRaw(requestParameters: AppWebhooksIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Returns one webhook regardless of whether it was created via this API or Settings → Developer → Configure Webhook — same fields either way. The secret is never echoed here; read it from GET /app/developer/settings (console webhook) or the create/rotate-secret response (only shown once).
     * Get a webhook
     */
    appWebhooksIdGet(requestParameters: AppWebhooksIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for appWebhooksIdPatch without sending the request
     * @param {string} id Webhook ID
     * @param {object} [body] { url?: string, events?: string[], description?: string }
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    appWebhooksIdPatchRequestOpts(requestParameters: AppWebhooksIdPatchRequest): Promise<runtime.RequestOpts>;

    /**
     * Sparse update — only url/events/description fields present in the body are changed. The id and secret never change; rotate the secret via POST /app/webhooks/{id}/rotate-secret.
     * @summary Update a webhook
     * @param {string} id Webhook ID
     * @param {object} [body] { url?: string, events?: string[], description?: string }
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    appWebhooksIdPatchRaw(requestParameters: AppWebhooksIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Sparse update — only url/events/description fields present in the body are changed. The id and secret never change; rotate the secret via POST /app/webhooks/{id}/rotate-secret.
     * Update a webhook
     */
    appWebhooksIdPatch(requestParameters: AppWebhooksIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for appWebhooksIdRotateSecretPost without sending the request
     * @param {string} id Webhook ID
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    appWebhooksIdRotateSecretPostRequestOpts(requestParameters: AppWebhooksIdRotateSecretPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Invalidates the old secret immediately — the new one is shown once in this response. Works on a webhook migrated from Settings → Developer → Configure Webhook the same way it works on one created via POST /app/webhooks.
     * @summary Rotate a webhook\'s signing secret
     * @param {string} id Webhook ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    appWebhooksIdRotateSecretPostRaw(requestParameters: AppWebhooksIdRotateSecretPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Invalidates the old secret immediately — the new one is shown once in this response. Works on a webhook migrated from Settings → Developer → Configure Webhook the same way it works on one created via POST /app/webhooks.
     * Rotate a webhook\'s signing secret
     */
    appWebhooksIdRotateSecretPost(requestParameters: AppWebhooksIdRotateSecretPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for appWebhooksIdTestPost without sending the request
     * @param {string} id Webhook ID
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    appWebhooksIdTestPostRequestOpts(requestParameters: AppWebhooksIdTestPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Fires a signed { event: \"test\", ... } payload at the webhook\'s URL asynchronously — the 200 here only confirms the request was queued, not that delivery succeeded.
     * @summary Send a test event
     * @param {string} id Webhook ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    appWebhooksIdTestPostRaw(requestParameters: AppWebhooksIdTestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Fires a signed { event: \"test\", ... } payload at the webhook\'s URL asynchronously — the 200 here only confirms the request was queued, not that delivery succeeded.
     * Send a test event
     */
    appWebhooksIdTestPost(requestParameters: AppWebhooksIdTestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Creates request options for appWebhooksPost without sending the request
     * @param {object} body { url: string, events: string[], description?: string }
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    appWebhooksPostRequestOpts(requestParameters: AppWebhooksPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Registers a webhook subscribed to the given events. The response\'s secret is shown once — every delivery to this URL is signed with it (see Verifying signatures in the webhooks guide). A webhook created here and one configured via Settings → Developer → Configure Webhook are the same kind of object — GET /app/webhooks lists both, signed the same way.
     * @summary Register a webhook
     * @param {object} body { url: string, events: string[], description?: string }
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    appWebhooksPostRaw(requestParameters: AppWebhooksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Registers a webhook subscribed to the given events. The response\'s secret is shown once — every delivery to this URL is signed with it (see Verifying signatures in the webhooks guide). A webhook created here and one configured via Settings → Developer → Configure Webhook are the same kind of object — GET /app/webhooks lists both, signed the same way.
     * Register a webhook
     */
    appWebhooksPost(requestParameters: AppWebhooksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

}

/**
 * 
 */
export class WebhooksApi extends runtime.BaseAPI implements WebhooksApiInterface {

    /**
     * Creates request options for appWebhooksEventsGet without sending the request
     */
    async appWebhooksEventsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/app/webhooks/events`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List subscribable webhook event names
     */
    async appWebhooksEventsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.appWebhooksEventsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * List subscribable webhook event names
     */
    async appWebhooksEventsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.appWebhooksEventsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for appWebhooksGet without sending the request
     */
    async appWebhooksGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/app/webhooks`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List registered webhooks
     */
    async appWebhooksGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.appWebhooksGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * List registered webhooks
     */
    async appWebhooksGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.appWebhooksGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for appWebhooksIdDelete without sending the request
     */
    async appWebhooksIdDeleteRequestOpts(requestParameters: AppWebhooksIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling appWebhooksIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/app/webhooks/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Deleting the webhook backing Settings → Developer → Configure Webhook resets that page to \"not configured\" rather than leaving it pointing at a dangling id.
     * Delete a webhook
     */
    async appWebhooksIdDeleteRaw(requestParameters: AppWebhooksIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.appWebhooksIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Deleting the webhook backing Settings → Developer → Configure Webhook resets that page to \"not configured\" rather than leaving it pointing at a dangling id.
     * Delete a webhook
     */
    async appWebhooksIdDelete(requestParameters: AppWebhooksIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.appWebhooksIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for appWebhooksIdGet without sending the request
     */
    async appWebhooksIdGetRequestOpts(requestParameters: AppWebhooksIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling appWebhooksIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/app/webhooks/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns one webhook regardless of whether it was created via this API or Settings → Developer → Configure Webhook — same fields either way. The secret is never echoed here; read it from GET /app/developer/settings (console webhook) or the create/rotate-secret response (only shown once).
     * Get a webhook
     */
    async appWebhooksIdGetRaw(requestParameters: AppWebhooksIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.appWebhooksIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Returns one webhook regardless of whether it was created via this API or Settings → Developer → Configure Webhook — same fields either way. The secret is never echoed here; read it from GET /app/developer/settings (console webhook) or the create/rotate-secret response (only shown once).
     * Get a webhook
     */
    async appWebhooksIdGet(requestParameters: AppWebhooksIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.appWebhooksIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for appWebhooksIdPatch without sending the request
     */
    async appWebhooksIdPatchRequestOpts(requestParameters: AppWebhooksIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling appWebhooksIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/app/webhooks/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Sparse update — only url/events/description fields present in the body are changed. The id and secret never change; rotate the secret via POST /app/webhooks/{id}/rotate-secret.
     * Update a webhook
     */
    async appWebhooksIdPatchRaw(requestParameters: AppWebhooksIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.appWebhooksIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Sparse update — only url/events/description fields present in the body are changed. The id and secret never change; rotate the secret via POST /app/webhooks/{id}/rotate-secret.
     * Update a webhook
     */
    async appWebhooksIdPatch(requestParameters: AppWebhooksIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.appWebhooksIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for appWebhooksIdRotateSecretPost without sending the request
     */
    async appWebhooksIdRotateSecretPostRequestOpts(requestParameters: AppWebhooksIdRotateSecretPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling appWebhooksIdRotateSecretPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/app/webhooks/{id}/rotate-secret`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Invalidates the old secret immediately — the new one is shown once in this response. Works on a webhook migrated from Settings → Developer → Configure Webhook the same way it works on one created via POST /app/webhooks.
     * Rotate a webhook\'s signing secret
     */
    async appWebhooksIdRotateSecretPostRaw(requestParameters: AppWebhooksIdRotateSecretPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.appWebhooksIdRotateSecretPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Invalidates the old secret immediately — the new one is shown once in this response. Works on a webhook migrated from Settings → Developer → Configure Webhook the same way it works on one created via POST /app/webhooks.
     * Rotate a webhook\'s signing secret
     */
    async appWebhooksIdRotateSecretPost(requestParameters: AppWebhooksIdRotateSecretPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.appWebhooksIdRotateSecretPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for appWebhooksIdTestPost without sending the request
     */
    async appWebhooksIdTestPostRequestOpts(requestParameters: AppWebhooksIdTestPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling appWebhooksIdTestPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/app/webhooks/{id}/test`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Fires a signed { event: \"test\", ... } payload at the webhook\'s URL asynchronously — the 200 here only confirms the request was queued, not that delivery succeeded.
     * Send a test event
     */
    async appWebhooksIdTestPostRaw(requestParameters: AppWebhooksIdTestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.appWebhooksIdTestPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Fires a signed { event: \"test\", ... } payload at the webhook\'s URL asynchronously — the 200 here only confirms the request was queued, not that delivery succeeded.
     * Send a test event
     */
    async appWebhooksIdTestPost(requestParameters: AppWebhooksIdTestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.appWebhooksIdTestPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for appWebhooksPost without sending the request
     */
    async appWebhooksPostRequestOpts(requestParameters: AppWebhooksPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling appWebhooksPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/app/webhooks`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Registers a webhook subscribed to the given events. The response\'s secret is shown once — every delivery to this URL is signed with it (see Verifying signatures in the webhooks guide). A webhook created here and one configured via Settings → Developer → Configure Webhook are the same kind of object — GET /app/webhooks lists both, signed the same way.
     * Register a webhook
     */
    async appWebhooksPostRaw(requestParameters: AppWebhooksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.appWebhooksPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Registers a webhook subscribed to the given events. The response\'s secret is shown once — every delivery to this URL is signed with it (see Verifying signatures in the webhooks guide). A webhook created here and one configured via Settings → Developer → Configure Webhook are the same kind of object — GET /app/webhooks lists both, signed the same way.
     * Register a webhook
     */
    async appWebhooksPost(requestParameters: AppWebhooksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.appWebhooksPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
