/* tslint:disable */
/* eslint-disable */
/**
 * Splashify Pro API
 * REST endpoints for two product surfaces: 1. **Public API** under /public/_* — WhatsApp messaging, contacts, conversations, transactional email, Meta Conversions API. Authenticate with sk_live_… keys. 2. **Partner Email API** under /partner/email/_* — AWS-SES-shaped resold email platform: identities, configuration sets, templates, suppression, send, send-template, send-bulk, send-raw, quotas, stats, reputation, events. Authenticate with pk_live_… keys. SDKs for Node.js, Python, and PHP are auto-generated from this spec.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@splashifypro.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface PublicApisUsersPostRequest {
    offset?: number;
    limit?: number;
    body?: object;
}

export interface PublicContactsDeletePostRequest {
    body: object;
}

export interface PublicContactsNotesPostRequest {
    body: object;
}

export interface PublicContactsPostRequest {
    body: object;
}

export interface PublicContactsTagsPostRequest {
    body: object;
}

export interface PublicContactsTagsRemovePostRequest {
    body: object;
}

/**
 * ContactsApi - interface
 * 
 * @export
 * @interface ContactsApiInterface
 */
export interface ContactsApiInterface {
    /**
     * Returns a paginated list of contacts (customers) for the authenticated account. Filters are applied in-memory and support traits: created_at_utc, modified_at_utc, phone_number, name, email, whatsapp_opted_in, plus any custom column from the contact\'s column_data.
     * @summary List contacts (paginated, filterable)
     * @param {number} [offset] Pagination offset (default 0)
     * @param {number} [limit] Page size (default 100, max 500)
     * @param {object} [body] Optional filter object: {filters:[{trait,op,val}]}
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactsApiInterface
     */
    publicApisUsersPostRaw(requestParameters: PublicApisUsersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Returns a paginated list of contacts (customers) for the authenticated account. Filters are applied in-memory and support traits: created_at_utc, modified_at_utc, phone_number, name, email, whatsapp_opted_in, plus any custom column from the contact\'s column_data.
     * List contacts (paginated, filterable)
     */
    publicApisUsersPost(requestParameters: PublicApisUsersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Permanently delete a contact and its conversation history.
     * @summary Delete a contact
     * @param {object} body { phone_number | contact_id }
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactsApiInterface
     */
    publicContactsDeletePostRaw(requestParameters: PublicContactsDeletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Permanently delete a contact and its conversation history.
     * Delete a contact
     */
    publicContactsDeletePost(requestParameters: PublicContactsDeletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Append (default) or replace the free-text notes on a contact.
     * @summary Add a note to a contact
     * @param {object} body { phone_number | contact_id, note, append }
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactsApiInterface
     */
    publicContactsNotesPostRaw(requestParameters: PublicContactsNotesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Append (default) or replace the free-text notes on a contact.
     * Add a note to a contact
     */
    publicContactsNotesPost(requestParameters: PublicContactsNotesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Add a new contact to your Splashify workspace.
     * @summary Create a contact
     * @param {object} body Contact payload (phone_number, display_name, …)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactsApiInterface
     */
    publicContactsPostRaw(requestParameters: PublicContactsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Add a new contact to your Splashify workspace.
     * Create a contact
     */
    publicContactsPost(requestParameters: PublicContactsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Add one or more tags to a contact. Existing tags are preserved.
     * @summary Assign tags to a contact
     * @param {object} body { phone_number | contact_id, tags: [] }
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactsApiInterface
     */
    publicContactsTagsPostRaw(requestParameters: PublicContactsTagsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Add one or more tags to a contact. Existing tags are preserved.
     * Assign tags to a contact
     */
    publicContactsTagsPost(requestParameters: PublicContactsTagsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Remove one or more tags from a contact.
     * @summary Remove tags from a contact
     * @param {object} body { phone_number | contact_id, tags: [] }
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactsApiInterface
     */
    publicContactsTagsRemovePostRaw(requestParameters: PublicContactsTagsRemovePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Remove one or more tags from a contact.
     * Remove tags from a contact
     */
    publicContactsTagsRemovePost(requestParameters: PublicContactsTagsRemovePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

}

/**
 * 
 */
export class ContactsApi extends runtime.BaseAPI implements ContactsApiInterface {

    /**
     * Returns a paginated list of contacts (customers) for the authenticated account. Filters are applied in-memory and support traits: created_at_utc, modified_at_utc, phone_number, name, email, whatsapp_opted_in, plus any custom column from the contact\'s column_data.
     * List contacts (paginated, filterable)
     */
    async publicApisUsersPostRaw(requestParameters: PublicApisUsersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const queryParameters: any = {};

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/apis/users`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Returns a paginated list of contacts (customers) for the authenticated account. Filters are applied in-memory and support traits: created_at_utc, modified_at_utc, phone_number, name, email, whatsapp_opted_in, plus any custom column from the contact\'s column_data.
     * List contacts (paginated, filterable)
     */
    async publicApisUsersPost(requestParameters: PublicApisUsersPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicApisUsersPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Permanently delete a contact and its conversation history.
     * Delete a contact
     */
    async publicContactsDeletePostRaw(requestParameters: PublicContactsDeletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling publicContactsDeletePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/contacts/delete`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Permanently delete a contact and its conversation history.
     * Delete a contact
     */
    async publicContactsDeletePost(requestParameters: PublicContactsDeletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicContactsDeletePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Append (default) or replace the free-text notes on a contact.
     * Add a note to a contact
     */
    async publicContactsNotesPostRaw(requestParameters: PublicContactsNotesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling publicContactsNotesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/contacts/notes`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Append (default) or replace the free-text notes on a contact.
     * Add a note to a contact
     */
    async publicContactsNotesPost(requestParameters: PublicContactsNotesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicContactsNotesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Add a new contact to your Splashify workspace.
     * Create a contact
     */
    async publicContactsPostRaw(requestParameters: PublicContactsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling publicContactsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/contacts`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Add a new contact to your Splashify workspace.
     * Create a contact
     */
    async publicContactsPost(requestParameters: PublicContactsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicContactsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Add one or more tags to a contact. Existing tags are preserved.
     * Assign tags to a contact
     */
    async publicContactsTagsPostRaw(requestParameters: PublicContactsTagsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling publicContactsTagsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/contacts/tags`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Add one or more tags to a contact. Existing tags are preserved.
     * Assign tags to a contact
     */
    async publicContactsTagsPost(requestParameters: PublicContactsTagsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicContactsTagsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove one or more tags from a contact.
     * Remove tags from a contact
     */
    async publicContactsTagsRemovePostRaw(requestParameters: PublicContactsTagsRemovePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling publicContactsTagsRemovePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/contacts/tags/remove`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Remove one or more tags from a contact.
     * Remove tags from a contact
     */
    async publicContactsTagsRemovePost(requestParameters: PublicContactsTagsRemovePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicContactsTagsRemovePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
