/* tslint:disable */
/* eslint-disable */
/**
 * Splashify Pro API
 * REST endpoints for two product surfaces: 1. **Public API** under /public/_* — WhatsApp messaging, contacts, conversations, transactional email, Meta Conversions API. Authenticate with sk_live_… keys. 2. **Partner Email API** under /partner/email/_* — AWS-SES-shaped resold email platform: identities, configuration sets, templates, suppression, send, send-template, send-bulk, send-raw, quotas, stats, reputation, events. Authenticate with pk_live_… keys. SDKs for Node.js, Python, and PHP are auto-generated from this spec.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@splashifypro.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface PublicAssignmentPostRequest {
    body: object;
}

/**
 * ConversationsApi - interface
 * 
 * @export
 * @interface ConversationsApiInterface
 */
export interface ConversationsApiInterface {
    /**
     * Routes a conversation to a specific team member by their email address. Conversation is identified by the customer\'s phone number. Both must belong to the authenticated account.
     * @summary Assign a chat to a team member
     * @param {object} body Assignment payload (user_phone_number, agent_email)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConversationsApiInterface
     */
    publicAssignmentPostRaw(requestParameters: PublicAssignmentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Routes a conversation to a specific team member by their email address. Conversation is identified by the customer\'s phone number. Both must belong to the authenticated account.
     * Assign a chat to a team member
     */
    publicAssignmentPost(requestParameters: PublicAssignmentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

}

/**
 * 
 */
export class ConversationsApi extends runtime.BaseAPI implements ConversationsApiInterface {

    /**
     * Routes a conversation to a specific team member by their email address. Conversation is identified by the customer\'s phone number. Both must belong to the authenticated account.
     * Assign a chat to a team member
     */
    async publicAssignmentPostRaw(requestParameters: PublicAssignmentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling publicAssignmentPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/assignment`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Routes a conversation to a specific team member by their email address. Conversation is identified by the customer\'s phone number. Both must belong to the authenticated account.
     * Assign a chat to a team member
     */
    async publicAssignmentPost(requestParameters: PublicAssignmentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicAssignmentPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
