/* tslint:disable */
/* eslint-disable */
/**
 * Splashify Pro API
 * REST endpoints for two product surfaces: 1. **Public API** under /public/_* — WhatsApp messaging, contacts, conversations, transactional email, Meta Conversions API. Authenticate with sk_live_… keys. 2. **Partner Email API** under /partner/email/_* — AWS-SES-shaped resold email platform: identities, configuration sets, templates, suppression, send, send-template, send-bulk, send-raw, quotas, stats, reputation, events. Authenticate with pk_live_… keys. SDKs for Node.js, Python, and PHP are auto-generated from this spec.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@splashifypro.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface PublicMessagePostRequest {
    body: object;
}

/**
 * MessagesApi - interface
 * 
 * @export
 * @interface MessagesApiInterface
 */
export interface MessagesApiInterface {
    /**
     * Send any supported WhatsApp message type to a contact. See type-specific request examples in the per-message docs.
     * @summary Send a WhatsApp message
     * @param {object} body Send message payload (type, phoneNumber, data)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagesApiInterface
     */
    publicMessagePostRaw(requestParameters: PublicMessagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Send any supported WhatsApp message type to a contact. See type-specific request examples in the per-message docs.
     * Send a WhatsApp message
     */
    publicMessagePost(requestParameters: PublicMessagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

}

/**
 * 
 */
export class MessagesApi extends runtime.BaseAPI implements MessagesApiInterface {

    /**
     * Send any supported WhatsApp message type to a contact. See type-specific request examples in the per-message docs.
     * Send a WhatsApp message
     */
    async publicMessagePostRaw(requestParameters: PublicMessagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling publicMessagePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/message`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Send any supported WhatsApp message type to a contact. See type-specific request examples in the per-message docs.
     * Send a WhatsApp message
     */
    async publicMessagePost(requestParameters: PublicMessagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicMessagePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
