/* tslint:disable */
/* eslint-disable */
/**
 * Splashify Pro API
 * REST endpoints for two product surfaces: 1. **Public API** under /public/_* — WhatsApp messaging, contacts, conversations, transactional email, Meta Conversions API. Authenticate with sk_live_… keys. 2. **Partner Email API** under /partner/email/_* — AWS-SES-shaped resold email platform: identities, configuration sets, templates, suppression, send, send-template, send-bulk, send-raw, quotas, stats, reputation, events. Authenticate with pk_live_… keys. SDKs for Node.js, Python, and PHP are auto-generated from this spec.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@splashifypro.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface PublicCapiSendEventPostRequest {
    body: object;
}

/**
 * MetaConversionsApi - interface
 * 
 * @export
 * @interface MetaConversionsApiInterface
 */
export interface MetaConversionsApiInterface {
    /**
     * Fire a server-side Meta Pixel / Conversions API event for a contact identified by phone number. Useful for ROI attribution on Click-to-WhatsApp ads. Event names: Lead, Purchase, AddToCart, etc. Requires Meta Ads OAuth completed in the dashboard.
     * @summary Send a Meta Conversion API event
     * @param {object} body CAPI payload (event_name, phone_number, value, currency)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MetaConversionsApiInterface
     */
    publicCapiSendEventPostRaw(requestParameters: PublicCapiSendEventPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Fire a server-side Meta Pixel / Conversions API event for a contact identified by phone number. Useful for ROI attribution on Click-to-WhatsApp ads. Event names: Lead, Purchase, AddToCart, etc. Requires Meta Ads OAuth completed in the dashboard.
     * Send a Meta Conversion API event
     */
    publicCapiSendEventPost(requestParameters: PublicCapiSendEventPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

}

/**
 * 
 */
export class MetaConversionsApi extends runtime.BaseAPI implements MetaConversionsApiInterface {

    /**
     * Fire a server-side Meta Pixel / Conversions API event for a contact identified by phone number. Useful for ROI attribution on Click-to-WhatsApp ads. Event names: Lead, Purchase, AddToCart, etc. Requires Meta Ads OAuth completed in the dashboard.
     * Send a Meta Conversion API event
     */
    async publicCapiSendEventPostRaw(requestParameters: PublicCapiSendEventPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling publicCapiSendEventPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/capi/send-event`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Fire a server-side Meta Pixel / Conversions API event for a contact identified by phone number. Useful for ROI attribution on Click-to-WhatsApp ads. Event names: Lead, Purchase, AddToCart, etc. Requires Meta Ads OAuth completed in the dashboard.
     * Send a Meta Conversion API event
     */
    async publicCapiSendEventPost(requestParameters: PublicCapiSendEventPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicCapiSendEventPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
