/* tslint:disable */
/* eslint-disable */
/**
 * Splashify Pro API
 * REST endpoints for two product surfaces: 1. **Public API** under /public/_* — WhatsApp messaging, contacts, conversations, transactional email, Meta Conversions API. Authenticate with sk_live_… keys. 2. **Partner Email API** under /partner/email/_* — AWS-SES-shaped resold email platform: identities, configuration sets, templates, suppression, send, send-template, send-bulk, send-raw, quotas, stats, reputation, events. Authenticate with pk_live_… keys. SDKs for Node.js, Python, and PHP are auto-generated from this spec.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@splashifypro.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface PartnerEmailStatsGetRequest {
    days?: number;
    configSetId?: string;
}

/**
 * PartnerEmailStatsApi - interface
 * 
 * @export
 * @interface PartnerEmailStatsApiInterface
 */
export interface PartnerEmailStatsApiInterface {
    /**
     * Returns the partner\'s daily send quota, peak send rate, sandbox flag, today\'s send count, and reputation status. Mirrors AWS SES GetSendQuota.
     * @summary Get sending quotas
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnerEmailStatsApiInterface
     */
    partnerEmailQuotasGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Returns the partner\'s daily send quota, peak send rate, sandbox flag, today\'s send count, and reputation status. Mirrors AWS SES GetSendQuota.
     * Get sending quotas
     */
    partnerEmailQuotasGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Day-by-day counters for sent / delivered / bounced / complained / opened / clicked / rejected over the last N days. Filterable by configuration set.
     * @summary Get sending statistics
     * @param {number} [days] Window size (default 30, max 90)
     * @param {string} [configSetId] Filter to one configuration set
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnerEmailStatsApiInterface
     */
    partnerEmailStatsGetRaw(requestParameters: PartnerEmailStatsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Day-by-day counters for sent / delivered / bounced / complained / opened / clicked / rejected over the last N days. Filterable by configuration set.
     * Get sending statistics
     */
    partnerEmailStatsGet(requestParameters: PartnerEmailStatsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

}

/**
 * 
 */
export class PartnerEmailStatsApi extends runtime.BaseAPI implements PartnerEmailStatsApiInterface {

    /**
     * Returns the partner\'s daily send quota, peak send rate, sandbox flag, today\'s send count, and reputation status. Mirrors AWS SES GetSendQuota.
     * Get sending quotas
     */
    async partnerEmailQuotasGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/partner/email/quotas`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Returns the partner\'s daily send quota, peak send rate, sandbox flag, today\'s send count, and reputation status. Mirrors AWS SES GetSendQuota.
     * Get sending quotas
     */
    async partnerEmailQuotasGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.partnerEmailQuotasGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Day-by-day counters for sent / delivered / bounced / complained / opened / clicked / rejected over the last N days. Filterable by configuration set.
     * Get sending statistics
     */
    async partnerEmailStatsGetRaw(requestParameters: PartnerEmailStatsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const queryParameters: any = {};

        if (requestParameters['days'] != null) {
            queryParameters['days'] = requestParameters['days'];
        }

        if (requestParameters['configSetId'] != null) {
            queryParameters['config_set_id'] = requestParameters['configSetId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/partner/email/stats`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Day-by-day counters for sent / delivered / bounced / complained / opened / clicked / rejected over the last N days. Filterable by configuration set.
     * Get sending statistics
     */
    async partnerEmailStatsGet(requestParameters: PartnerEmailStatsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.partnerEmailStatsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
