/* tslint:disable */
/* eslint-disable */
/**
 * Splashify Pro API
 * REST endpoints for two product surfaces: 1. **Public API** under /public/_* — WhatsApp messaging, contacts, conversations, transactional email, Meta Conversions API. Authenticate with sk_live_… keys. 2. **Partner Email API** under /partner/email/_* — AWS-SES-shaped resold email platform: identities, configuration sets, templates, suppression, send, send-template, send-bulk, send-raw, quotas, stats, reputation, events. Authenticate with pk_live_… keys. SDKs for Node.js, Python, and PHP are auto-generated from this spec.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@splashifypro.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface PartnerEmailIdentitiesPostRequest {
    body: object;
}

export interface PartnerEmailIdentitiesTypeValueVerifyPostRequest {
    type: string;
    value: string;
}

/**
 * PartnerEmailIdentitiesApi - interface
 * 
 * @export
 * @interface PartnerEmailIdentitiesApiInterface
 */
export interface PartnerEmailIdentitiesApiInterface {
    /**
     * Returns every verified or pending sending identity (domains + verified email addresses) for the authenticated partner.
     * @summary List sending identities
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnerEmailIdentitiesApiInterface
     */
    partnerEmailIdentitiesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Returns every verified or pending sending identity (domains + verified email addresses) for the authenticated partner.
     * List sending identities
     */
    partnerEmailIdentitiesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Register a new sending identity. For DOMAIN type returns the SPF + DKIM CNAME + DMARC TXT records to publish; for EMAIL_ADDRESS type sends a one-time confirmation token.
     * @summary Create sending identity
     * @param {object} body Create identity payload (identity_type, identity_value)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnerEmailIdentitiesApiInterface
     */
    partnerEmailIdentitiesPostRaw(requestParameters: PartnerEmailIdentitiesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Register a new sending identity. For DOMAIN type returns the SPF + DKIM CNAME + DMARC TXT records to publish; for EMAIL_ADDRESS type sends a one-time confirmation token.
     * Create sending identity
     */
    partnerEmailIdentitiesPost(requestParameters: PartnerEmailIdentitiesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Re-runs DNS verification (SPF + DKIM + DMARC checks) on a domain identity. Triggered after publishing the DNS records returned from CreateIdentity.
     * @summary Verify identity
     * @param {string} type DOMAIN or EMAIL_ADDRESS
     * @param {string} value Domain (yourdomain.com) or email address
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnerEmailIdentitiesApiInterface
     */
    partnerEmailIdentitiesTypeValueVerifyPostRaw(requestParameters: PartnerEmailIdentitiesTypeValueVerifyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Re-runs DNS verification (SPF + DKIM + DMARC checks) on a domain identity. Triggered after publishing the DNS records returned from CreateIdentity.
     * Verify identity
     */
    partnerEmailIdentitiesTypeValueVerifyPost(requestParameters: PartnerEmailIdentitiesTypeValueVerifyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

}

/**
 * 
 */
export class PartnerEmailIdentitiesApi extends runtime.BaseAPI implements PartnerEmailIdentitiesApiInterface {

    /**
     * Returns every verified or pending sending identity (domains + verified email addresses) for the authenticated partner.
     * List sending identities
     */
    async partnerEmailIdentitiesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/partner/email/identities`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Returns every verified or pending sending identity (domains + verified email addresses) for the authenticated partner.
     * List sending identities
     */
    async partnerEmailIdentitiesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.partnerEmailIdentitiesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Register a new sending identity. For DOMAIN type returns the SPF + DKIM CNAME + DMARC TXT records to publish; for EMAIL_ADDRESS type sends a one-time confirmation token.
     * Create sending identity
     */
    async partnerEmailIdentitiesPostRaw(requestParameters: PartnerEmailIdentitiesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling partnerEmailIdentitiesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/partner/email/identities`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Register a new sending identity. For DOMAIN type returns the SPF + DKIM CNAME + DMARC TXT records to publish; for EMAIL_ADDRESS type sends a one-time confirmation token.
     * Create sending identity
     */
    async partnerEmailIdentitiesPost(requestParameters: PartnerEmailIdentitiesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.partnerEmailIdentitiesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Re-runs DNS verification (SPF + DKIM + DMARC checks) on a domain identity. Triggered after publishing the DNS records returned from CreateIdentity.
     * Verify identity
     */
    async partnerEmailIdentitiesTypeValueVerifyPostRaw(requestParameters: PartnerEmailIdentitiesTypeValueVerifyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling partnerEmailIdentitiesTypeValueVerifyPost().'
            );
        }

        if (requestParameters['value'] == null) {
            throw new runtime.RequiredError(
                'value',
                'Required parameter "value" was null or undefined when calling partnerEmailIdentitiesTypeValueVerifyPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/partner/email/identities/{type}/{value}/verify`;
        urlPath = urlPath.replace(`{${"type"}}`, encodeURIComponent(String(requestParameters['type'])));
        urlPath = urlPath.replace(`{${"value"}}`, encodeURIComponent(String(requestParameters['value'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Re-runs DNS verification (SPF + DKIM + DMARC checks) on a domain identity. Triggered after publishing the DNS records returned from CreateIdentity.
     * Verify identity
     */
    async partnerEmailIdentitiesTypeValueVerifyPost(requestParameters: PartnerEmailIdentitiesTypeValueVerifyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.partnerEmailIdentitiesTypeValueVerifyPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
