/* tslint:disable */
/* eslint-disable */
/**
 * Splashify Pro API
 * REST endpoints for two product surfaces: 1. **Public API** under /public/_* — WhatsApp messaging, contacts, conversations, transactional email, Meta Conversions API. Authenticate with sk_live_… keys. 2. **Partner Email API** under /partner/email/_* — AWS-SES-shaped resold email platform: identities, configuration sets, templates, suppression, send, send-template, send-bulk, send-raw, quotas, stats, reputation, events. Authenticate with pk_live_… keys. SDKs for Node.js, Python, and PHP are auto-generated from this spec.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@splashifypro.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface PublicRcsSendPostRequest {
    body: object;
}

export interface PublicRcsSendTemplatePostRequest {
    body: object;
}

/**
 * RCSApi - interface
 * 
 * @export
 * @interface RCSApiInterface
 */
export interface RCSApiInterface {
    /**
     * Send any RCS message type — text, media, card or multiple_cards.
     * @summary Send an RCS message
     * @param {object} body RCS message payload (to, type, and the type-specific fields)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RCSApiInterface
     */
    publicRcsSendPostRaw(requestParameters: PublicRcsSendPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Send any RCS message type — text, media, card or multiple_cards.
     * Send an RCS message
     */
    publicRcsSendPost(requestParameters: PublicRcsSendPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

    /**
     * Send a stored, approved RCS template. Positional {#varN#} placeholders are filled from the variables array, in order.
     * @summary Send an RCS template message
     * @param {object} body RCS template payload (to, template_id, variables)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RCSApiInterface
     */
    publicRcsSendTemplatePostRaw(requestParameters: PublicRcsSendTemplatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>>;

    /**
     * Send a stored, approved RCS template. Positional {#varN#} placeholders are filled from the variables array, in order.
     * Send an RCS template message
     */
    publicRcsSendTemplatePost(requestParameters: PublicRcsSendTemplatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }>;

}

/**
 * 
 */
export class RCSApi extends runtime.BaseAPI implements RCSApiInterface {

    /**
     * Send any RCS message type — text, media, card or multiple_cards.
     * Send an RCS message
     */
    async publicRcsSendPostRaw(requestParameters: PublicRcsSendPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling publicRcsSendPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/rcs/send`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Send any RCS message type — text, media, card or multiple_cards.
     * Send an RCS message
     */
    async publicRcsSendPost(requestParameters: PublicRcsSendPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicRcsSendPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Send a stored, approved RCS template. Positional {#varN#} placeholders are filled from the variables array, in order.
     * Send an RCS template message
     */
    async publicRcsSendTemplatePostRaw(requestParameters: PublicRcsSendTemplatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling publicRcsSendTemplatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/public/rcs/send-template`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Send a stored, approved RCS template. Positional {#varN#} placeholders are filled from the variables array, in order.
     * Send an RCS template message
     */
    async publicRcsSendTemplatePost(requestParameters: PublicRcsSendTemplatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.publicRcsSendTemplatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
