/* tslint:disable */
/* eslint-disable */
/**
 * Splashify Pro API
 * REST endpoints for three product surfaces: 1. **Public API** under /public/_* — WhatsApp messaging, contacts, conversations, transactional email, Meta Conversions API. Authenticate with sk_live_… keys. 2. **Partner Email API** under /partner/email/_* — AWS-SES-shaped resold email platform: identities, configuration sets, templates, suppression, send, send-template, send-bulk, send-raw, quotas, stats, reputation, events. Authenticate with pk_live_… keys. 3. **App API** under /app/_* — the same surface the customer dashboard and the CLI/OpenClaw integrations use, authenticated with either an app session or an oc_live_… access token (`splashify auth login` / Settings → Developer → Access Tokens). Coverage here is partial — only endpoints touched by integrator reports are annotated so far, not the full surface. SDKs for Node.js, Python, and PHP are auto-generated from this spec.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@splashifypro.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandlersUpdateWebhookRequest
 */
export interface HandlersUpdateWebhookRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof HandlersUpdateWebhookRequest
     */
    webhookEvents?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof HandlersUpdateWebhookRequest
     */
    webhookUrl?: string;
}

/**
 * Check if a given object implements the HandlersUpdateWebhookRequest interface.
 */
export function instanceOfHandlersUpdateWebhookRequest(value: object): value is HandlersUpdateWebhookRequest {
    return true;
}

export function HandlersUpdateWebhookRequestFromJSON(json: any): HandlersUpdateWebhookRequest {
    return HandlersUpdateWebhookRequestFromJSONTyped(json, false);
}

export function HandlersUpdateWebhookRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlersUpdateWebhookRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'webhookEvents': json['webhook_events'] == null ? undefined : json['webhook_events'],
        'webhookUrl': json['webhook_url'] == null ? undefined : json['webhook_url'],
    };
}

export function HandlersUpdateWebhookRequestToJSON(json: any): HandlersUpdateWebhookRequest {
    return HandlersUpdateWebhookRequestToJSONTyped(json, false);
}

export function HandlersUpdateWebhookRequestToJSONTyped(value?: HandlersUpdateWebhookRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'webhook_events': value['webhookEvents'],
        'webhook_url': value['webhookUrl'],
    };
}

