/* tslint:disable */
/* eslint-disable */
/**
 * Splashify Pro API
 * REST endpoints for two product surfaces: 1. **Public API** under /public/_* — WhatsApp messaging, contacts, conversations, transactional email, Meta Conversions API. Authenticate with sk_live_… keys. 2. **Partner Email API** under /partner/email/_* — AWS-SES-shaped resold email platform: identities, configuration sets, templates, suppression, send, send-template, send-bulk, send-raw, quotas, stats, reputation, events. Authenticate with pk_live_… keys. SDKs for Node.js, Python, and PHP are auto-generated from this spec.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@splashifypro.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandlersCheckCapabilityRequest
 */
export interface HandlersCheckCapabilityRequest {
    /**
     * 
     * @type {string}
     * @memberof HandlersCheckCapabilityRequest
     */
    botId?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersCheckCapabilityRequest
     */
    phone?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof HandlersCheckCapabilityRequest
     */
    phones?: Array<string>;
}

/**
 * Check if a given object implements the HandlersCheckCapabilityRequest interface.
 */
export function instanceOfHandlersCheckCapabilityRequest(value: object): value is HandlersCheckCapabilityRequest {
    return true;
}

export function HandlersCheckCapabilityRequestFromJSON(json: any): HandlersCheckCapabilityRequest {
    return HandlersCheckCapabilityRequestFromJSONTyped(json, false);
}

export function HandlersCheckCapabilityRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlersCheckCapabilityRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'botId': json['bot_id'] == null ? undefined : json['bot_id'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'phones': json['phones'] == null ? undefined : json['phones'],
    };
}

export function HandlersCheckCapabilityRequestToJSON(json: any): HandlersCheckCapabilityRequest {
    return HandlersCheckCapabilityRequestToJSONTyped(json, false);
}

export function HandlersCheckCapabilityRequestToJSONTyped(value?: HandlersCheckCapabilityRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bot_id': value['botId'],
        'phone': value['phone'],
        'phones': value['phones'],
    };
}

