/* tslint:disable */
/* eslint-disable */
/**
 * Splashify Pro API
 * REST endpoints for three product surfaces: 1. **Public API** under /public/_* — WhatsApp messaging, contacts, conversations, transactional email, Meta Conversions API. Authenticate with sk_live_… keys. 2. **Partner Email API** under /partner/email/_* — AWS-SES-shaped resold email platform: identities, configuration sets, templates, suppression, send, send-template, send-bulk, send-raw, quotas, stats, reputation, events. Authenticate with pk_live_… keys. 3. **App API** under /app/_* — the same surface the customer dashboard and the CLI/OpenClaw integrations use, authenticated with either an app session or an oc_live_… access token (`splashify auth login` / Settings → Developer → Access Tokens). Coverage here is partial — only endpoints touched by integrator reports are annotated so far, not the full surface. SDKs for Node.js, Python, and PHP are auto-generated from this spec.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@splashifypro.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandlersUpdateOptOutErrorRequest
 */
export interface HandlersUpdateOptOutErrorRequest {
    /**
     * 
     * @type {boolean}
     * @memberof HandlersUpdateOptOutErrorRequest
     */
    enabled?: boolean;
}

/**
 * Check if a given object implements the HandlersUpdateOptOutErrorRequest interface.
 */
export function instanceOfHandlersUpdateOptOutErrorRequest(value: object): value is HandlersUpdateOptOutErrorRequest {
    return true;
}

export function HandlersUpdateOptOutErrorRequestFromJSON(json: any): HandlersUpdateOptOutErrorRequest {
    return HandlersUpdateOptOutErrorRequestFromJSONTyped(json, false);
}

export function HandlersUpdateOptOutErrorRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlersUpdateOptOutErrorRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
    };
}

export function HandlersUpdateOptOutErrorRequestToJSON(json: any): HandlersUpdateOptOutErrorRequest {
    return HandlersUpdateOptOutErrorRequestToJSONTyped(json, false);
}

export function HandlersUpdateOptOutErrorRequestToJSONTyped(value?: HandlersUpdateOptOutErrorRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
    };
}

